
-- SQL generated by wms-data-generator
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-wms-schema.sql file instead
--
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
-- 🚚 DELIVEROO (C) 2025 🚚
-- 🚚   SHIP THAT SHIT   🚚
-- 🚚   Spółka Akcyjna   🚚
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
--
-- Zatrudniamy! https://shorturl.at/G98Ej


-- Clean up previous tables
DROP TABLE IF EXISTS cargo_event_history CASCADE;
DROP TABLE IF EXISTS cargo_event_type CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS storage_record CASCADE;
DROP TABLE IF EXISTS storage_reservation CASCADE;
DROP TABLE IF EXISTS storage_request CASCADE;
DROP TABLE IF EXISTS employee_warehouse CASCADE;
DROP TABLE IF EXISTS party_role CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS party_relationship CASCADE;
DROP TABLE IF EXISTS party_contact CASCADE;
DROP TABLE IF EXISTS party CASCADE;
DROP TABLE IF EXISTS capacity CASCADE;
DROP TABLE IF EXISTS shelf CASCADE;
DROP TABLE IF EXISTS rack CASCADE;
DROP TABLE IF EXISTS aisle CASCADE;
DROP TABLE IF EXISTS zone CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS location CASCADE;

-- 1. LOCATIONS
CREATE TABLE location (
    location_id SERIAL PRIMARY KEY,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL
);

-- 2. WAREHOUSES
CREATE TABLE warehouse (
    warehouse_id SERIAL PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES location(location_id),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Basic FK index only
CREATE INDEX idx_warehouse_location_id ON warehouse(location_id);

-- 3. ZONES
CREATE TABLE zone (
    zone_id SERIAL PRIMARY KEY,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_zone_warehouse_id ON zone(warehouse_id);
-- The code is the first segment of the composed shelf path (A-01-R001-L4)
CREATE UNIQUE INDEX uq_zone_code ON zone(warehouse_id, code);

-- 4. AISLES
CREATE TABLE aisle (
    aisle_id SERIAL PRIMARY KEY,
    zone_id INTEGER NOT NULL REFERENCES zone(zone_id),
    label TEXT NOT NULL,
    width INTEGER NOT NULL,
    width_unit TEXT NOT NULL CHECK (width_unit IN ('mm','cm','m')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_aisle_zone_id ON aisle(zone_id);
CREATE UNIQUE INDEX uq_aisle_label ON aisle(zone_id, label);

-- 5. RACKS
CREATE TABLE rack (
    rack_id SERIAL PRIMARY KEY,
    aisle_id INTEGER NOT NULL REFERENCES aisle(aisle_id),
    label TEXT NOT NULL,
    max_height INTEGER NOT NULL,
    height_unit TEXT NOT NULL CHECK (height_unit IN ('mm','cm','m')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rack_aisle_id ON rack(aisle_id);
CREATE UNIQUE INDEX uq_rack_label ON rack(aisle_id, label);

-- 6. SHELVES
-- max_weight is expressed in kilograms, max_volume in cubic metres.
-- Unlike aisle.width and rack.max_height these columns carry no unit column,
-- so the API normalises to these base units on write.
CREATE TABLE shelf (
    shelf_id SERIAL PRIMARY KEY,
    rack_id INTEGER NOT NULL REFERENCES rack(rack_id),
    level TEXT NOT NULL,
    max_weight NUMERIC NOT NULL,
    max_volume NUMERIC NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_shelf_rack_id ON shelf(rack_id);
CREATE UNIQUE INDEX uq_shelf_level ON shelf(rack_id, level);
COMMENT ON COLUMN shelf.max_weight IS 'Declared capacity in kilograms (kg)';
COMMENT ON COLUMN shelf.max_volume IS 'Declared capacity in cubic metres (m3)';

-- 7. CAPACITY
CREATE TABLE capacity (
    capacity_id SERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('WAREHOUSE','ZONE','RACK','SHELF')),
    entity_id INTEGER NOT NULL,
    value NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    description TEXT
);
-- Composite index exists, but likely insufficient for complex aggregations without covering columns
CREATE INDEX idx_capacity_entity ON capacity(entity_type, entity_id);

-- 8. PARTY
CREATE TABLE party (
    party_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT, -- Important: No index here implies full scan on search
    contact_phone TEXT,
    data JSONB, -- Important: No GIN index here
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. PARTY CONTACTS
CREATE TABLE party_contact (
    contact_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    details TEXT NOT NULL
);
CREATE INDEX idx_party_contact_party_id ON party_contact(party_id);

-- 10. PARTY RELATIONSHIP
CREATE TABLE party_relationship (
    relationship_id SERIAL PRIMARY KEY,
    party_id_primary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    party_id_secondary INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    notes TEXT
);
CREATE INDEX idx_party_relationship_primary ON party_relationship(party_id_primary);
CREATE INDEX idx_party_relationship_secondary ON party_relationship(party_id_secondary);

-- 11. ADDRESS
CREATE TABLE address (
    address_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    address_type TEXT NOT NULL CHECK (address_type IN ('BILLING','SHIPPING','CORPORATE','PERSONAL','OTHER'))
);
CREATE INDEX idx_address_party_id ON address(party_id);

-- 12. ROLES
CREATE TABLE role (
    role_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL CHECK (name IN ('DIRECTOR','WAREHOUSE_MANAGER','LOGISTICS_COORDINATOR','STORAGE_APPROVER','OPERATOR')),
    description TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_role_name ON role(name);

-- 13. PARTY ROLES
CREATE TABLE party_role (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (party_id, role_id)
);
CREATE INDEX idx_party_role_party_id ON party_role(party_id);
CREATE INDEX idx_party_role_role_id ON party_role(role_id);

-- 14. EMPLOYEE-WAREHOUSE
CREATE TABLE employee_warehouse (
    party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id) ON DELETE CASCADE,
    assigned_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_until TIMESTAMP,
    PRIMARY KEY (party_id, warehouse_id, assigned_from)
);
CREATE INDEX idx_employee_warehouse_party_id ON employee_warehouse(party_id);
CREATE INDEX idx_employee_warehouse_warehouse ON employee_warehouse(warehouse_id);

-- 15. STORAGE REQUESTS
CREATE TABLE storage_request (
    request_id SERIAL PRIMARY KEY,
    issuing_party_id INTEGER NOT NULL REFERENCES party(party_id),
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    requested_entry_date TIMESTAMP NOT NULL,
    requested_exit_date TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACCEPTED','REJECTED')) DEFAULT 'PENDING',
    decisive_party_id INTEGER REFERENCES party(party_id),
    decision_date TIMESTAMP
);
CREATE INDEX idx_storage_request_issuing_party_id ON storage_request(issuing_party_id);
CREATE INDEX idx_storage_request_warehouse_id ON storage_request(warehouse_id);
CREATE INDEX idx_storage_request_decisive_party_id ON storage_request(decisive_party_id);

-- 16. STORAGE RESERVATIONS
CREATE TABLE storage_reservation (
    reservation_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    reserved_weight NUMERIC NOT NULL,
    reserved_volume NUMERIC NOT NULL,
    reserved_from TIMESTAMP NOT NULL,
    reserved_until TIMESTAMP NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','ACTIVE','EXPIRED','CANCELLED')) DEFAULT 'PENDING'
);
CREATE INDEX idx_storage_reservation_request_id ON storage_reservation(request_id);
CREATE INDEX idx_storage_reservation_party_id ON storage_reservation(party_id);
CREATE INDEX idx_storage_reservation_shelf_id ON storage_reservation(shelf_id);

-- 17. STORAGE RECORDS
CREATE TABLE storage_record (
    storage_record_id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES storage_request(request_id),
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    shelf_id INTEGER NOT NULL REFERENCES shelf(shelf_id),
    actual_entry_date TIMESTAMP NOT NULL,
    actual_exit_date TIMESTAMP,
    cargo_description TEXT NOT NULL,
    cargo_weight NUMERIC NOT NULL,
    cargo_volume NUMERIC NOT NULL
);
CREATE INDEX idx_storage_record_request_id ON storage_record(request_id);
CREATE INDEX idx_storage_record_party_id ON storage_record(party_id);
CREATE INDEX idx_storage_record_shelf_id ON storage_record(shelf_id);

-- 18. PAYMENTS
CREATE TABLE payment (
    payment_id SERIAL PRIMARY KEY,
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','PAID','FAILED','CANCELLED')) DEFAULT 'PENDING',
    payment_date TIMESTAMP,
    external_reference TEXT
);
CREATE INDEX idx_payment_party_id ON payment(party_id);
CREATE INDEX idx_payment_storage_record_id ON payment(storage_record_id);

-- 19. CARGO EVENT TYPES
CREATE TABLE cargo_event_type (
    event_type_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);
CREATE UNIQUE INDEX idx_cargo_event_type_name ON cargo_event_type(name);

-- 20. CARGO EVENT HISTORY
CREATE TABLE cargo_event_history (
    event_id SERIAL PRIMARY KEY,
    party_id INTEGER NOT NULL REFERENCES party(party_id),
    storage_record_id INTEGER NOT NULL REFERENCES storage_record(storage_record_id) ON DELETE CASCADE,
    event_type_id INTEGER NOT NULL REFERENCES cargo_event_type(event_type_id),
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB
);
CREATE INDEX idx_cargo_event_history_party_id ON cargo_event_history(party_id);
CREATE INDEX idx_cargo_event_history_storage_record_id ON cargo_event_history(storage_record_id);
CREATE INDEX idx_cargo_event_history_event_type_id ON cargo_event_history(event_type_id);

-- Locations
INSERT INTO location (location_id, address, city, postal_code, country) VALUES
(1, 'ul. Wichrowa 89', 'Janki', '05-090', 'Poland');

-- Warehouses
INSERT INTO warehouse (warehouse_id, location_id, name, description) VALUES
(1, 1, 'Main Deliveroo Warehouse', 'Main warehouse for Deliveroo in Poland');

-- Roles
INSERT INTO role (role_id, name, description) VALUES
(1, 'DIRECTOR', 'Executive director overseeing all warehouse operations and strategic planning.'),
(2, 'WAREHOUSE_MANAGER', 'Oversees all warehouse operations, staff management, and safety protocols.'),
(3, 'LOGISTICS_COORDINATOR', 'Manages logistics, distribution processes, and supply chain coordination.'),
(4, 'STORAGE_APPROVER', 'Reviews and approves storage requests and reservation decisions.'),
(5, 'OPERATOR', 'Handles day-to-day warehouse operations including receiving, shipping, and inventory management.');

-- Contractor and Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(1, 'Brown, Clark and Moore', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2026-02-14 18:59:53.543729', '2025-10-15 18:48:35.300972'),
(2, 'Collins-Johnson', '{"type": "contractor_company", "tax_id_number": "5413763266", "status": "ACTIVE"}'::jsonb, '2025-06-23 06:57:23.697371', '2025-11-25 19:52:37.496457'),
(3, 'Bradley-Spencer', '{"type": "contractor_company", "tax_id_number": "4363489770", "status": "ACTIVE"}'::jsonb, '2026-03-17 16:59:32.049101', '2026-08-19 19:09:55.292562'),
(4, 'Wilson Inc', '{"type": "contractor_company", "tax_id_number": "2816297328", "status": "ACTIVE"}'::jsonb, '2025-04-21 09:56:35.273226', '2026-08-21 10:31:31.667111'),
(5, 'Robinson, Hill and Foster', '{"type": "contractor_company", "tax_id_number": "7190026433", "status": "ACTIVE"}'::jsonb, '2026-08-21 18:30:19.865531', '2026-08-19 02:58:17.135916'),
(6, 'Brooks Group', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2026-06-29 07:00:53.287759', '2026-07-16 22:29:31.796833'),
(7, 'Ochoa LLC', '{"type": "contractor_company", "tax_id_number": "2342826545", "status": "INACTIVE"}'::jsonb, '2025-10-10 13:05:42.391649', '2026-05-25 12:13:53.824699'),
(8, 'Peterson and Sons', '{"type": "contractor_company", "tax_id_number": "8133310671", "status": "ACTIVE"}'::jsonb, '2024-09-14 02:05:39.985308', '2025-11-05 04:42:42.663479'),
(9, 'Beltran-Curry', '{"type": "contractor_company", "tax_id_number": "6037690600", "status": "ACTIVE"}'::jsonb, '2025-10-26 17:54:55.032231', '2026-06-17 02:30:25.541415'),
(10, 'Pennington Ltd', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2026-02-15 09:13:47.775131', '2026-03-17 20:08:18.187255'),
(11, 'Jacobson, Clark and Mcintyre', '{"type": "contractor_company", "tax_id_number": "6158616290", "status": "ACTIVE"}'::jsonb, '2025-06-19 10:04:10.469503', '2026-04-08 22:51:45.342049'),
(12, 'Hobbs LLC', '{"type": "contractor_company", "tax_id_number": "3003920212", "status": "ACTIVE"}'::jsonb, '2026-02-28 07:05:48.365685', '2025-10-19 12:45:41.612340'),
(13, 'Elliott Inc', '{"type": "contractor_company", "tax_id_number": "8662213334", "status": "ACTIVE"}'::jsonb, '2025-11-17 11:39:51.628588', '2026-03-23 16:19:00.331074'),
(14, 'Black, Allison and Mccullough', '{"type": "contractor_company", "tax_id_number": "6007542397", "status": "ACTIVE"}'::jsonb, '2025-11-09 09:22:10.777738', '2026-03-18 19:58:01.319715'),
(15, 'Guzman-Thomas', '{"type": "contractor_company", "tax_id_number": "4286214401", "status": "ACTIVE"}'::jsonb, '2026-07-11 07:10:07.414802', '2026-01-18 16:50:59.842588'),
(16, 'Hahn-Stewart', '{"type": "contractor_company", "tax_id_number": "6512737569", "status": "ACTIVE"}'::jsonb, '2025-10-03 21:33:34.329924', '2025-12-26 16:14:48.299270'),
(17, 'Meyer-Evans', '{"type": "contractor_company", "tax_id_number": "8540817737", "status": "ACTIVE"}'::jsonb, '2024-10-17 12:20:09.206270', '2025-11-26 04:36:57.622907'),
(18, 'Bates and Sons', '{"type": "contractor_company", "tax_id_number": "2172406436", "status": "ACTIVE"}'::jsonb, '2025-01-11 06:00:58.296429', '2026-05-11 21:05:18.234801'),
(19, 'Casey, Freeman and Nolan', '{"type": "contractor_company", "tax_id_number": "2773401656", "status": "ACTIVE"}'::jsonb, '2026-02-12 04:26:48.529402', '2025-11-17 22:12:23.311059'),
(20, 'Thompson Ltd', '{"type": "contractor_company", "tax_id_number": "0253825268", "status": "ACTIVE"}'::jsonb, '2026-06-24 03:59:55.113155', '2026-02-22 16:19:35.683160'),
(21, 'Buchanan-York', '{"type": "contractor_company", "tax_id_number": "8692336686", "status": "ACTIVE"}'::jsonb, '2024-12-23 18:17:17.129846', '2026-07-15 13:39:24.019835'),
(22, 'Martinez-Riley', '{"type": "contractor_company", "tax_id_number": "9251112229", "status": "ACTIVE"}'::jsonb, '2026-07-28 09:26:32.577781', '2025-11-19 03:35:16.534454'),
(23, 'Johnson, Thomas and Griffin', '{"type": "contractor_company", "tax_id_number": "7162192678", "status": "ACTIVE"}'::jsonb, '2026-07-14 18:35:40.190782', '2025-09-30 06:08:50.143728'),
(24, 'Williams-Reed', '{"type": "contractor_company", "tax_id_number": "6331371263", "status": "INACTIVE"}'::jsonb, '2025-05-07 08:43:20.278916', '2026-07-12 06:28:36.142301'),
(25, 'Gross, Hawkins and Gray', '{"type": "contractor_company", "tax_id_number": null, "status": "ACTIVE"}'::jsonb, '2026-04-19 10:46:50.012986', '2025-11-23 21:42:05.610037'),
(26, 'Ford, Tucker and Bright', '{"type": "contractor_company", "tax_id_number": "5622247213", "status": "INACTIVE"}'::jsonb, '2024-11-01 13:06:50.813123', '2025-10-30 02:57:36.053759'),
(27, 'Dawson, Arnold and Wood', '{"type": "contractor_company", "tax_id_number": "6642772009", "status": "ACTIVE"}'::jsonb, '2025-09-15 01:34:01.533893', '2026-07-07 05:58:37.198420'),
(28, 'Reid and Sons', '{"type": "contractor_company", "tax_id_number": "2684145132", "status": "ACTIVE"}'::jsonb, '2025-07-07 09:42:42.715969', '2025-11-13 10:27:04.395245'),
(29, 'Larson, Coleman and Bush', '{"type": "contractor_company", "tax_id_number": "8249044668", "status": "ACTIVE"}'::jsonb, '2025-08-16 22:46:58.341590', '2026-03-19 00:51:39.929039'),
(30, 'Mcdonald PLC', '{"type": "contractor_company", "tax_id_number": "0173696833", "status": "ACTIVE"}'::jsonb, '2024-10-04 22:48:55.910718', '2026-02-03 12:23:46.185262'),
(31, 'Hammond and Sons', '{"type": "contractor_company", "tax_id_number": "2826141058", "status": "ACTIVE"}'::jsonb, '2025-02-11 22:06:50.414884', '2025-11-18 21:20:51.851931'),
(32, 'Williams and Sons', '{"type": "contractor_company", "tax_id_number": "3005795763", "status": "ACTIVE"}'::jsonb, '2024-11-07 14:37:30.217272', '2025-09-07 05:17:28.716898'),
(33, 'Baker, Fields and Erickson', '{"type": "contractor_company", "tax_id_number": "7711067247", "status": "ACTIVE"}'::jsonb, '2026-06-07 03:26:37.461513', '2025-11-06 22:31:18.725114'),
(34, 'Mendez PLC', '{"type": "contractor_company", "tax_id_number": "8064836989", "status": "ACTIVE"}'::jsonb, '2026-08-01 02:05:53.499514', '2026-03-31 19:28:11.137412'),
(35, 'Robinson-Rogers', '{"type": "contractor_company", "tax_id_number": "7538988192", "status": "ACTIVE"}'::jsonb, '2025-11-19 23:55:26.159518', '2026-06-16 05:55:31.448528'),
(36, 'Rose, Austin and Reid', '{"type": "contractor_company", "tax_id_number": "4983871691", "status": "ACTIVE"}'::jsonb, '2025-04-29 09:34:46.824295', '2026-05-28 02:56:06.080615'),
(37, 'Ferguson-Cook', '{"type": "contractor_company", "tax_id_number": "8549224019", "status": "ACTIVE"}'::jsonb, '2024-09-29 17:16:57.659205', '2026-07-08 15:39:09.097955'),
(38, 'Conrad, Reed and Williams', '{"type": "contractor_company", "tax_id_number": "1229758695", "status": "ACTIVE"}'::jsonb, '2025-10-17 00:09:52.779035', '2026-05-21 11:45:39.218965'),
(39, 'Knight, Kim and Wilson', '{"type": "contractor_company", "tax_id_number": "2178482339", "status": "ACTIVE"}'::jsonb, '2024-10-26 13:14:34.259356', '2026-02-18 15:59:40.424537'),
(40, 'Anderson, Herrera and Adams', '{"type": "contractor_company", "tax_id_number": "7367855408", "status": "ACTIVE"}'::jsonb, '2025-09-16 03:00:40.308274', '2026-08-25 23:19:13.008448'),
(41, 'Floyd, Castillo and Haley', '{"type": "contractor_company", "tax_id_number": "0805470806", "status": "ACTIVE"}'::jsonb, '2025-03-18 02:38:00.728122', '2025-11-16 16:38:46.223106'),
(42, 'Martin-Phillips', '{"type": "contractor_company", "tax_id_number": "8045056636", "status": "ACTIVE"}'::jsonb, '2025-10-20 04:58:49.230356', '2026-02-03 17:52:25.098502'),
(43, 'Hughes-Bernard', '{"type": "contractor_company", "tax_id_number": "5960779682", "status": "ACTIVE"}'::jsonb, '2024-12-17 23:44:47.675597', '2025-10-13 16:08:15.840620'),
(44, 'Thornton-Watts', '{"type": "contractor_company", "tax_id_number": "2974384574", "status": "ACTIVE"}'::jsonb, '2026-03-27 13:10:07.597354', '2026-08-26 11:18:39.352565'),
(45, 'Durham-Smith', '{"type": "contractor_company", "tax_id_number": "8664598419", "status": "ACTIVE"}'::jsonb, '2024-12-04 23:54:28.149187', '2026-08-14 12:07:51.730113'),
(46, 'Jensen-Lopez', '{"type": "contractor_company", "tax_id_number": "3589570977", "status": "INACTIVE"}'::jsonb, '2024-12-23 19:57:08.017783', '2025-10-30 11:46:01.393720'),
(47, 'Andrade-Brooks', '{"type": "contractor_company", "tax_id_number": "6032062398", "status": "ACTIVE"}'::jsonb, '2026-03-17 16:38:01.316916', '2025-09-24 05:10:48.059052'),
(48, 'Brown, Shepard and Lee', '{"type": "contractor_company", "tax_id_number": "7987285987", "status": "ACTIVE"}'::jsonb, '2024-12-21 03:15:02.053236', '2026-05-01 12:21:26.592767'),
(49, 'Gomez-Rhodes', '{"type": "contractor_company", "tax_id_number": "0547867672", "status": "ACTIVE"}'::jsonb, '2026-05-04 09:55:16.306749', '2025-11-22 03:01:07.154525'),
(50, 'Love PLC', '{"type": "contractor_company", "tax_id_number": "2121518769", "status": "ACTIVE"}'::jsonb, '2025-03-13 04:13:35.622193', '2026-07-09 00:20:39.259373'),
(71, 'Brett Moreno', '{"type": "contractor_employee", "job_title": "Psychologist, counselling"}'::jsonb, '2026-02-11 02:40:07.710236', '2026-08-27 14:06:13.098634'),
(72, 'Rhonda Blanchard', '{"type": "contractor_employee", "job_title": "Financial manager"}'::jsonb, '2026-07-21 21:49:05.983142', '2026-08-27 14:10:18.898710'),
(73, 'Lucas Lane', '{"type": "contractor_employee", "job_title": "Geneticist, molecular"}'::jsonb, '2026-01-18 05:42:06.368449', '2026-08-27 14:09:04.388782'),
(74, 'Ryan Anderson', '{"type": "contractor_employee", "job_title": "Forest/woodland manager"}'::jsonb, '2026-04-19 01:44:51.891832', '2026-08-27 14:08:31.489579'),
(75, 'Angela Foley', '{"type": "contractor_employee", "job_title": "Armed forces technical officer"}'::jsonb, '2026-01-26 07:39:28.022076', '2026-08-27 14:07:19.094407'),
(76, 'Rebecca Aguilar', '{"type": "contractor_employee", "job_title": "Engineer, biomedical"}'::jsonb, '2026-06-17 22:24:48.306753', '2026-08-27 14:09:51.966296'),
(77, 'Haley Maldonado', '{"type": "contractor_employee", "job_title": "Forensic scientist"}'::jsonb, '2026-06-15 19:36:03.296060', '2026-08-27 14:10:36.255156'),
(78, 'Jesse Romero', '{"type": "contractor_employee", "job_title": "Farm manager"}'::jsonb, '2026-01-14 09:38:06.060053', '2026-08-27 14:07:47.858727'),
(79, 'Dawn Hayes', '{"type": "contractor_employee", "job_title": "Engineer, biomedical"}'::jsonb, '2025-09-26 03:27:15.811140', '2026-08-27 14:07:56.977345'),
(80, 'Dennis Davis', '{"type": "contractor_employee", "job_title": "Management consultant"}'::jsonb, '2025-11-21 07:31:56.964675', '2026-08-27 14:08:42.123733'),
(81, 'Mary Webb', '{"type": "contractor_employee", "job_title": "Gaffer"}'::jsonb, '2026-03-20 14:20:21.730474', '2026-08-27 14:08:10.857117'),
(82, 'Christian Johnson', '{"type": "contractor_employee", "job_title": "Educational psychologist"}'::jsonb, '2026-06-30 11:21:10.428246', '2026-08-27 14:09:44.254694'),
(83, 'Jill Tate', '{"type": "contractor_employee", "job_title": "Surveyor, hydrographic"}'::jsonb, '2025-11-06 08:46:30.353803', '2026-08-27 14:08:17.256063'),
(84, 'Scott Martinez', '{"type": "contractor_employee", "job_title": "Mudlogger"}'::jsonb, '2026-02-13 05:26:18.630285', '2026-08-27 14:10:18.601836'),
(85, 'Jamie Contreras', '{"type": "contractor_employee", "job_title": "Colour technologist"}'::jsonb, '2025-09-17 05:53:11.747113', '2026-08-27 14:09:29.587301'),
(86, 'Christopher Freeman', '{"type": "contractor_employee", "job_title": "Freight forwarder"}'::jsonb, '2026-05-18 10:43:08.325608', '2026-08-27 14:07:52.563775'),
(87, 'Robert Hill', '{"type": "contractor_employee", "job_title": "Therapist, nutritional"}'::jsonb, '2026-02-25 10:10:41.493222', '2026-08-27 14:08:46.954329'),
(88, 'Mr. Mike Oliver', '{"type": "contractor_employee", "job_title": "Orthoptist"}'::jsonb, '2025-09-22 01:39:01.567977', '2026-08-27 14:10:26.381862'),
(89, 'Sergio Jacobs', '{"type": "contractor_employee", "job_title": "Science writer"}'::jsonb, '2026-04-09 18:24:59.726127', '2026-08-27 14:11:44.282153'),
(90, 'Albert Nguyen', '{"type": "contractor_employee", "job_title": "Chartered loss adjuster"}'::jsonb, '2025-10-19 03:10:18.084764', '2026-08-27 14:08:21.819287'),
(91, 'Kathryn Perry', '{"type": "contractor_employee", "job_title": "Network engineer"}'::jsonb, '2026-07-23 08:42:57.496391', '2026-08-27 14:08:35.349533'),
(92, 'Melissa Randall', '{"type": "contractor_employee", "job_title": "Engineer, chemical"}'::jsonb, '2026-01-23 01:35:30.625747', '2026-08-27 14:09:10.245039'),
(93, 'Kenneth Garcia', '{"type": "contractor_employee", "job_title": "Building surveyor"}'::jsonb, '2025-09-07 09:04:43.679946', '2026-08-27 14:09:23.176019'),
(94, 'Keith Martin', '{"type": "contractor_employee", "job_title": "Psychotherapist"}'::jsonb, '2026-03-23 00:32:18.656090', '2026-08-27 14:07:20.679919'),
(95, 'Lauren Robinson', '{"type": "contractor_employee", "job_title": "Clinical biochemist"}'::jsonb, '2025-12-24 11:53:10.178648', '2026-08-27 14:10:31.360638'),
(96, 'Matthew Lambert', '{"type": "contractor_employee", "job_title": "Nurse, mental health"}'::jsonb, '2026-05-27 06:47:36.623159', '2026-08-27 14:08:54.867246'),
(97, 'Stephanie Stephenson', '{"type": "contractor_employee", "job_title": "Corporate investment banker"}'::jsonb, '2026-07-20 00:03:18.280527', '2026-08-27 14:10:49.542358'),
(98, 'Mr. Richard Williams', '{"type": "contractor_employee", "job_title": "Community education officer"}'::jsonb, '2026-02-02 07:40:52.496590', '2026-08-27 14:08:52.678261'),
(99, 'Derek Marshall', '{"type": "contractor_employee", "job_title": "Health promotion specialist"}'::jsonb, '2025-10-30 13:15:55.684814', '2026-08-27 14:07:08.416898'),
(100, 'Jay Steele', '{"type": "contractor_employee", "job_title": "IT technical support officer"}'::jsonb, '2026-04-21 14:18:36.509198', '2026-08-27 14:09:09.119253'),
(101, 'Victoria Jones', '{"type": "contractor_employee", "job_title": "Systems analyst"}'::jsonb, '2025-11-16 17:16:11.285197', '2026-08-27 14:06:55.125652'),
(102, 'Dr. Tina Williams', '{"type": "contractor_employee", "job_title": "Jewellery designer"}'::jsonb, '2026-05-05 08:41:27.582824', '2026-08-27 14:10:28.240864'),
(103, 'Robert Delacruz', '{"type": "contractor_employee", "job_title": "Education administrator"}'::jsonb, '2026-04-26 11:42:56.267827', '2026-08-27 14:10:02.621138'),
(104, 'Steven Cruz', '{"type": "contractor_employee", "job_title": "Proofreader"}'::jsonb, '2026-07-02 00:53:11.927778', '2026-08-27 14:08:31.689611'),
(105, 'Patricia Smith', '{"type": "contractor_employee", "job_title": "Research officer, trade union"}'::jsonb, '2026-06-25 23:22:48.941717', '2026-08-27 14:10:15.063960'),
(106, 'Natalie Williams', '{"type": "contractor_employee", "job_title": "Therapist, horticultural"}'::jsonb, '2026-05-07 18:23:03.268913', '2026-08-27 14:06:38.676841'),
(107, 'Michael Huff', '{"type": "contractor_employee", "job_title": "Heritage manager"}'::jsonb, '2026-08-04 16:30:27.446046', '2026-08-27 14:09:28.533166'),
(108, 'Dustin Cline', '{"type": "contractor_employee", "job_title": "Fast food restaurant manager"}'::jsonb, '2026-01-31 22:48:49.630161', '2026-08-27 14:09:56.354329'),
(109, 'Mary Wilson', '{"type": "contractor_employee", "job_title": "Medical technical officer"}'::jsonb, '2026-07-31 11:51:37.172190', '2026-08-27 14:10:48.328386'),
(110, 'Lisa Arnold', '{"type": "contractor_employee", "job_title": "Chiropractor"}'::jsonb, '2026-04-24 03:16:01.706906', '2026-08-27 14:11:45.459889'),
(111, 'Cynthia Chavez', '{"type": "contractor_employee", "job_title": "Restaurant manager, fast food"}'::jsonb, '2026-03-21 00:12:52.495934', '2026-08-27 14:10:54.276604'),
(112, 'Beverly Harvey', '{"type": "contractor_employee", "job_title": "Armed forces operational officer"}'::jsonb, '2025-12-18 10:32:10.302147', '2026-08-27 14:11:45.008934'),
(113, 'Susan Cunningham', '{"type": "contractor_employee", "job_title": "Building services engineer"}'::jsonb, '2026-06-02 22:59:18.827370', '2026-08-27 14:06:13.380705'),
(114, 'Mary Gonzales', '{"type": "contractor_employee", "job_title": "Warden/ranger"}'::jsonb, '2025-12-12 00:21:11.960466', '2026-08-27 14:06:20.419046'),
(115, 'Sara Moore', '{"type": "contractor_employee", "job_title": "Stage manager"}'::jsonb, '2025-11-11 07:41:23.620428', '2026-08-27 14:11:53.961789'),
(116, 'David Buchanan', '{"type": "contractor_employee", "job_title": "Materials engineer"}'::jsonb, '2026-05-03 16:47:58.115611', '2026-08-27 14:06:04.734900'),
(117, 'Carl Sanchez', '{"type": "contractor_employee", "job_title": "Archivist"}'::jsonb, '2026-06-15 14:35:56.097904', '2026-08-27 14:08:41.289519'),
(118, 'James Garrett', '{"type": "contractor_employee", "job_title": "Buyer, retail"}'::jsonb, '2026-05-21 01:31:06.514000', '2026-08-27 14:11:28.653483'),
(119, 'Brittney Roberson', '{"type": "contractor_employee", "job_title": "Financial manager"}'::jsonb, '2026-01-31 15:04:31.481483', '2026-08-27 14:07:36.155467'),
(120, 'Timothy Wells', '{"type": "contractor_employee", "job_title": "Physiological scientist"}'::jsonb, '2025-10-13 20:10:29.362089', '2026-08-27 14:09:30.614886'),
(121, 'Yolanda Reid', '{"type": "contractor_employee", "job_title": "Materials engineer"}'::jsonb, '2026-03-29 14:27:07.222590', '2026-08-27 14:08:45.204838'),
(122, 'Thomas Reed', '{"type": "contractor_employee", "job_title": "Pilot, airline"}'::jsonb, '2025-12-19 07:25:18.714339', '2026-08-27 14:10:50.488341'),
(123, 'Christopher Hawkins', '{"type": "contractor_employee", "job_title": "Banker"}'::jsonb, '2026-07-17 03:12:49.047567', '2026-08-27 14:08:56.790084'),
(124, 'Bailey Coleman', '{"type": "contractor_employee", "job_title": "Psychologist, counselling"}'::jsonb, '2026-05-24 23:31:52.804601', '2026-08-27 14:11:40.506628'),
(125, 'Edward Vaughan', '{"type": "contractor_employee", "job_title": "Geochemist"}'::jsonb, '2025-09-11 18:08:40.456003', '2026-08-27 14:08:50.678113'),
(126, 'Arthur Suarez', '{"type": "contractor_employee", "job_title": "Banker"}'::jsonb, '2025-09-29 13:03:55.172102', '2026-08-27 14:06:22.537227'),
(127, 'Kelly Huber', '{"type": "contractor_employee", "job_title": "Editor, commissioning"}'::jsonb, '2025-11-24 04:29:33.161275', '2026-08-27 14:11:38.664418'),
(128, 'Maria Harvey', '{"type": "contractor_employee", "job_title": "Communications engineer"}'::jsonb, '2025-12-17 12:57:02.552497', '2026-08-27 14:10:42.354952'),
(129, 'Jack Russo', '{"type": "contractor_employee", "job_title": "Ambulance person"}'::jsonb, '2025-08-27 11:10:02.242025', '2026-08-27 14:10:11.945875'),
(130, 'Katherine Carroll', '{"type": "contractor_employee", "job_title": "Midwife"}'::jsonb, '2025-09-11 00:29:27.440297', '2026-08-27 14:09:27.042004'),
(131, 'Abigail Smith', '{"type": "contractor_employee", "job_title": "Corporate investment banker"}'::jsonb, '2026-01-22 04:17:01.749647', '2026-08-27 14:08:38.522452'),
(132, 'Heidi Hess', '{"type": "contractor_employee", "job_title": "Community arts worker"}'::jsonb, '2026-08-26 09:06:52.432094', '2026-08-27 14:07:36.924943'),
(133, 'Alison Hoffman', '{"type": "contractor_employee", "job_title": "Nurse, children''s"}'::jsonb, '2026-07-11 07:50:52.804972', '2026-08-27 14:11:48.451306'),
(134, 'Candice Crawford', '{"type": "contractor_employee", "job_title": "Therapist, nutritional"}'::jsonb, '2026-07-15 15:50:03.416842', '2026-08-27 14:06:33.342854'),
(135, 'Greg Lee', '{"type": "contractor_employee", "job_title": "Forensic scientist"}'::jsonb, '2026-06-27 16:18:49.792202', '2026-08-27 14:08:16.676528'),
(136, 'Kimberly Gonzalez', '{"type": "contractor_employee", "job_title": "Health physicist"}'::jsonb, '2026-08-17 07:44:43.808043', '2026-08-27 14:11:25.178155'),
(137, 'Brian Edwards', '{"type": "contractor_employee", "job_title": "Seismic interpreter"}'::jsonb, '2026-05-07 01:22:06.228726', '2026-08-27 14:11:19.804464'),
(138, 'Marcus Hughes', '{"type": "contractor_employee", "job_title": "Animal technologist"}'::jsonb, '2026-04-22 18:53:25.034579', '2026-08-27 14:11:20.521705'),
(139, 'Jennifer Anderson', '{"type": "contractor_employee", "job_title": "Technical sales engineer"}'::jsonb, '2025-10-24 22:31:15.388533', '2026-08-27 14:06:07.396429'),
(140, 'Brandon Hicks', '{"type": "contractor_employee", "job_title": "Scientist, clinical (histocompatibility and immunogenetics)"}'::jsonb, '2025-11-11 21:06:47.860939', '2026-08-27 14:07:25.203121'),
(141, 'Ryan Alvarez', '{"type": "contractor_employee", "job_title": "Tree surgeon"}'::jsonb, '2026-05-17 21:52:31.650581', '2026-08-27 14:05:58.611017');

-- Party Relationships
INSERT INTO party_relationship (party_id_primary, party_id_secondary, relationship_type, valid_from) VALUES
(1, 71, 'REPRESENTATIVE', '2025-10-29 04:04:54.887209'),
(2, 72, 'REPRESENTATIVE', '2026-04-23 12:10:57.759577'),
(2, 73, 'REPRESENTATIVE', '2026-05-26 08:12:47.286801'),
(3, 74, 'REPRESENTATIVE', '2025-09-24 00:16:21.218993'),
(3, 75, 'REPRESENTATIVE', '2026-01-21 00:51:10.645113'),
(5, 76, 'REPRESENTATIVE', '2025-10-13 09:55:11.030829'),
(6, 77, 'REPRESENTATIVE', '2026-03-31 21:35:32.009801'),
(6, 78, 'REPRESENTATIVE', '2026-05-15 13:55:45.763801'),
(6, 79, 'REPRESENTATIVE', '2025-09-05 19:17:40.721240'),
(8, 80, 'REPRESENTATIVE', '2025-10-09 14:51:16.471306'),
(9, 81, 'REPRESENTATIVE', '2026-06-30 23:53:44.587473'),
(9, 82, 'REPRESENTATIVE', '2026-03-17 18:47:00.941592'),
(9, 83, 'REPRESENTATIVE', '2026-06-09 12:52:02.187667'),
(10, 84, 'REPRESENTATIVE', '2026-06-13 04:08:28.478850'),
(10, 85, 'REPRESENTATIVE', '2026-08-13 23:28:38.123239'),
(11, 86, 'REPRESENTATIVE', '2026-02-10 04:47:47.393450'),
(11, 87, 'REPRESENTATIVE', '2026-04-22 21:46:04.857781'),
(11, 88, 'REPRESENTATIVE', '2026-05-12 16:43:43.719275'),
(12, 89, 'REPRESENTATIVE', '2025-09-01 04:09:01.055593'),
(13, 90, 'REPRESENTATIVE', '2026-07-10 04:36:41.996492'),
(13, 91, 'REPRESENTATIVE', '2026-03-11 04:32:52.083755'),
(14, 92, 'REPRESENTATIVE', '2025-09-16 06:07:53.290971'),
(14, 93, 'REPRESENTATIVE', '2026-04-04 09:48:04.545490'),
(16, 94, 'REPRESENTATIVE', '2026-01-16 23:06:05.304069'),
(16, 95, 'REPRESENTATIVE', '2025-12-10 10:18:41.117625'),
(16, 96, 'REPRESENTATIVE', '2026-08-13 08:57:06.108006'),
(19, 97, 'REPRESENTATIVE', '2026-06-30 01:42:10.556555'),
(19, 98, 'REPRESENTATIVE', '2026-06-16 13:01:52.993682'),
(20, 99, 'REPRESENTATIVE', '2026-04-26 10:15:25.911499'),
(20, 100, 'REPRESENTATIVE', '2026-04-14 04:35:04.405025'),
(22, 101, 'REPRESENTATIVE', '2025-11-01 17:41:01.605581'),
(22, 102, 'REPRESENTATIVE', '2026-05-02 17:17:45.032327'),
(23, 103, 'REPRESENTATIVE', '2025-09-14 01:40:48.948226'),
(24, 104, 'REPRESENTATIVE', '2026-06-30 23:48:54.956038'),
(24, 105, 'REPRESENTATIVE', '2025-09-30 09:36:54.260182'),
(24, 106, 'REPRESENTATIVE', '2026-07-04 14:24:57.671181'),
(26, 107, 'REPRESENTATIVE', '2026-01-27 10:35:50.221587'),
(27, 108, 'REPRESENTATIVE', '2025-12-24 08:32:52.174248'),
(27, 109, 'REPRESENTATIVE', '2025-10-02 23:55:02.796658'),
(27, 110, 'REPRESENTATIVE', '2026-08-11 12:55:55.694871'),
(29, 111, 'REPRESENTATIVE', '2026-01-10 12:17:22.639435'),
(29, 112, 'REPRESENTATIVE', '2026-03-07 17:01:48.199083'),
(29, 113, 'REPRESENTATIVE', '2025-10-06 01:26:41.350358'),
(30, 114, 'REPRESENTATIVE', '2025-09-11 13:34:57.147543'),
(32, 115, 'REPRESENTATIVE', '2025-10-04 18:35:32.268988'),
(32, 116, 'REPRESENTATIVE', '2025-11-02 09:52:54.374716'),
(32, 117, 'REPRESENTATIVE', '2026-08-20 06:27:04.849375'),
(33, 118, 'REPRESENTATIVE', '2026-02-01 11:16:34.021341'),
(33, 119, 'REPRESENTATIVE', '2025-09-23 08:59:41.343554'),
(33, 120, 'REPRESENTATIVE', '2025-10-30 03:58:34.850195'),
(34, 121, 'REPRESENTATIVE', '2026-08-10 09:58:36.195432'),
(35, 122, 'REPRESENTATIVE', '2025-09-28 14:57:33.299059'),
(36, 123, 'REPRESENTATIVE', '2026-03-14 08:58:11.902776'),
(36, 124, 'REPRESENTATIVE', '2026-03-06 02:48:12.659851'),
(36, 125, 'REPRESENTATIVE', '2026-01-05 13:38:29.690054'),
(37, 126, 'REPRESENTATIVE', '2025-12-02 01:43:54.263412'),
(37, 127, 'REPRESENTATIVE', '2025-12-16 13:33:54.962287'),
(38, 128, 'REPRESENTATIVE', '2025-11-25 18:26:54.481144'),
(39, 129, 'REPRESENTATIVE', '2026-05-30 03:58:54.767585'),
(39, 130, 'REPRESENTATIVE', '2025-12-24 03:00:43.106771'),
(41, 131, 'REPRESENTATIVE', '2025-09-21 11:18:48.425841'),
(41, 132, 'REPRESENTATIVE', '2025-12-30 05:49:57.363393'),
(41, 133, 'REPRESENTATIVE', '2025-10-21 02:32:44.815391'),
(43, 134, 'REPRESENTATIVE', '2025-10-21 18:06:41.740869'),
(44, 135, 'REPRESENTATIVE', '2026-08-19 03:29:46.954436'),
(46, 136, 'REPRESENTATIVE', '2025-10-07 18:03:58.803964'),
(46, 137, 'REPRESENTATIVE', '2026-06-01 13:55:42.828356'),
(46, 138, 'REPRESENTATIVE', '2025-11-01 08:20:54.479825'),
(47, 139, 'REPRESENTATIVE', '2025-10-05 10:30:54.862788'),
(49, 140, 'REPRESENTATIVE', '2026-07-25 20:53:12.386674'),
(49, 141, 'REPRESENTATIVE', '2026-03-25 14:18:37.741208');

-- Party Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(1, 'EMAIL', 'info@brownclarkandmoore.com'),
(1, 'PHONE', '+1-895-557-2272x1544'),
(2, 'EMAIL', 'info@collins-johnson.com'),
(2, 'PHONE', '001-767-662-4784x651'),
(3, 'EMAIL', 'info@bradley-spencer.com'),
(3, 'PHONE', '207.916.2066'),
(4, 'EMAIL', 'info@wilsoninc.com'),
(5, 'EMAIL', 'info@robinsonhillandfoster.com'),
(5, 'PHONE', '(800)304-3075x5865'),
(6, 'EMAIL', 'info@brooksgroup.com'),
(6, 'PHONE', '+1-648-970-1679x876'),
(7, 'EMAIL', 'info@ochoallc.com'),
(7, 'PHONE', '(322)291-9348'),
(8, 'EMAIL', 'info@petersonandsons.com'),
(8, 'PHONE', '(835)968-7703x83992'),
(9, 'EMAIL', 'info@beltran-curry.com'),
(9, 'PHONE', '329.627.2735x9315'),
(10, 'EMAIL', 'info@penningtonltd.com'),
(10, 'PHONE', '001-250-246-3823x42905'),
(11, 'EMAIL', 'info@jacobsonclarkandmcintyre.com'),
(11, 'PHONE', '(853)528-3569x2402'),
(12, 'EMAIL', 'info@hobbsllc.com'),
(12, 'PHONE', '832-964-4290'),
(13, 'EMAIL', 'info@elliottinc.com'),
(14, 'EMAIL', 'info@blackallisonandmccullough.com'),
(15, 'EMAIL', 'info@guzman-thomas.com'),
(15, 'PHONE', '(293)306-6123'),
(16, 'EMAIL', 'info@hahn-stewart.com'),
(16, 'PHONE', '001-443-350-4290x42655'),
(17, 'EMAIL', 'info@meyer-evans.com'),
(17, 'PHONE', '508.959.2974x599'),
(18, 'EMAIL', 'info@batesandsons.com'),
(18, 'PHONE', '7144522888'),
(19, 'EMAIL', 'info@caseyfreemanandnolan.com'),
(19, 'PHONE', '+1-845-286-3513x115'),
(20, 'EMAIL', 'info@thompsonltd.com'),
(20, 'PHONE', '+1-987-837-4815x5705'),
(21, 'EMAIL', 'info@buchanan-york.com'),
(21, 'PHONE', '724.545.8726x4631'),
(22, 'EMAIL', 'info@martinez-riley.com'),
(22, 'PHONE', '001-592-828-7694'),
(23, 'EMAIL', 'info@johnsonthomasandgriffin.com'),
(23, 'PHONE', '001-271-276-7786x288'),
(24, 'EMAIL', 'info@williams-reed.com'),
(24, 'PHONE', '612-733-9487x847'),
(25, 'EMAIL', 'info@grosshawkinsandgray.com'),
(25, 'PHONE', '+1-809-607-3427x9466'),
(26, 'EMAIL', 'info@fordtuckerandbright.com'),
(26, 'PHONE', '(947)973-7349'),
(27, 'EMAIL', 'info@dawsonarnoldandwood.com'),
(27, 'PHONE', '(847)554-9437'),
(28, 'EMAIL', 'info@reidandsons.com'),
(28, 'PHONE', '878-598-4991x94899'),
(29, 'EMAIL', 'info@larsoncolemanandbush.com'),
(29, 'PHONE', '(228)515-3482'),
(30, 'EMAIL', 'info@mcdonaldplc.com'),
(31, 'EMAIL', 'info@hammondandsons.com'),
(31, 'PHONE', '321-468-7276'),
(32, 'EMAIL', 'info@williamsandsons.com'),
(32, 'PHONE', '553-441-6610x38478'),
(33, 'EMAIL', 'info@bakerfieldsanderickson.com'),
(33, 'PHONE', '486.558.1117x326'),
(34, 'EMAIL', 'info@mendezplc.com'),
(34, 'PHONE', '001-272-446-2721x888'),
(35, 'EMAIL', 'info@robinson-rogers.com'),
(35, 'PHONE', '704-514-2869x29303'),
(36, 'EMAIL', 'info@roseaustinandreid.com'),
(36, 'PHONE', '222-303-6844x5815'),
(37, 'EMAIL', 'info@ferguson-cook.com'),
(37, 'PHONE', '(220)613-8083'),
(38, 'EMAIL', 'info@conradreedandwilliams.com'),
(38, 'PHONE', '775.538.7239'),
(39, 'EMAIL', 'info@knightkimandwilson.com'),
(40, 'EMAIL', 'info@andersonherreraandadams.com'),
(41, 'EMAIL', 'info@floydcastilloandhaley.com'),
(41, 'PHONE', '(709)514-5117x426'),
(42, 'EMAIL', 'info@martin-phillips.com'),
(42, 'PHONE', '5002570411'),
(43, 'EMAIL', 'info@hughes-bernard.com'),
(43, 'PHONE', '(293)667-7828'),
(44, 'EMAIL', 'info@thornton-watts.com'),
(44, 'PHONE', '001-251-494-5023'),
(45, 'EMAIL', 'info@durham-smith.com'),
(45, 'PHONE', '595-711-5124x862'),
(46, 'EMAIL', 'info@jensen-lopez.com'),
(46, 'PHONE', '001-483-314-2203x25908'),
(47, 'EMAIL', 'info@andrade-brooks.com'),
(48, 'EMAIL', 'info@brownshepardandlee.com'),
(49, 'EMAIL', 'info@gomez-rhodes.com'),
(50, 'EMAIL', 'info@loveplc.com'),
(50, 'PHONE', '+1-609-489-7943x038'),
(71, 'EMAIL', 'brett.moreno@brownclarkandmoore.com'),
(71, 'PHONE', '001-767-860-9537x74932'),
(72, 'EMAIL', 'rhonda.blanchard@collins-johnson.com'),
(72, 'PHONE', '(785)578-5186x460'),
(73, 'EMAIL', 'lucas.lane@collins-johnson.com'),
(73, 'PHONE', '423.464.6800'),
(74, 'EMAIL', 'ryan.anderson@bradley-spencer.com'),
(74, 'PHONE', '985-509-7389x7759'),
(75, 'EMAIL', 'angela.foley@bradley-spencer.com'),
(75, 'PHONE', '(486)209-2975'),
(76, 'EMAIL', 'rebecca.aguilar@robinsonhillandfoster.com'),
(77, 'EMAIL', 'haley.maldonado@brooksgroup.com'),
(77, 'PHONE', '611.229.3804'),
(78, 'EMAIL', 'jesse.romero@brooksgroup.com'),
(78, 'PHONE', '517.504.6179x746'),
(79, 'EMAIL', 'dawn.hayes@brooksgroup.com'),
(79, 'PHONE', '410-910-9210x64118'),
(80, 'EMAIL', 'dennis.davis@petersonandsons.com'),
(80, 'PHONE', '485.570.3831x77740'),
(81, 'EMAIL', 'mary.webb@beltran-curry.com'),
(81, 'PHONE', '(784)866-9310x91873'),
(82, 'EMAIL', 'christian.johnson@beltran-curry.com'),
(82, 'PHONE', '+1-690-273-6585'),
(83, 'EMAIL', 'jill.tate@beltran-curry.com'),
(83, 'PHONE', '4678108007'),
(84, 'EMAIL', 'scott.martinez@penningtonltd.com'),
(84, 'PHONE', '957.940.1579x1551'),
(85, 'EMAIL', 'jamie.contreras@penningtonltd.com'),
(85, 'PHONE', '(429)998-4588'),
(86, 'EMAIL', 'christopher.freeman@jacobsonclarkandmcintyre.com'),
(86, 'PHONE', '387-668-4094x5297'),
(87, 'EMAIL', 'robert.hill@jacobsonclarkandmcintyre.com'),
(87, 'PHONE', '(458)963-1702x692'),
(88, 'EMAIL', 'mr..oliver@jacobsonclarkandmcintyre.com'),
(88, 'PHONE', '(882)440-0153x5593'),
(89, 'EMAIL', 'sergio.jacobs@hobbsllc.com'),
(89, 'PHONE', '+1-683-229-0215x5725'),
(90, 'EMAIL', 'albert.nguyen@elliottinc.com'),
(91, 'EMAIL', 'kathryn.perry@elliottinc.com'),
(91, 'PHONE', '825-787-0045'),
(92, 'EMAIL', 'melissa.randall@blackallisonandmccullough.com'),
(92, 'PHONE', '216-324-9937x578'),
(93, 'EMAIL', 'kenneth.garcia@blackallisonandmccullough.com'),
(93, 'PHONE', '001-539-699-6255x959'),
(94, 'EMAIL', 'keith.martin@hahn-stewart.com'),
(94, 'PHONE', '+1-843-663-2117x4279'),
(95, 'EMAIL', 'lauren.robinson@hahn-stewart.com'),
(95, 'PHONE', '959-457-3214'),
(96, 'EMAIL', 'matthew.lambert@hahn-stewart.com'),
(96, 'PHONE', '(528)754-3165'),
(97, 'EMAIL', 'stephanie.stephenson@caseyfreemanandnolan.com'),
(97, 'PHONE', '940.869.6203x8193'),
(98, 'EMAIL', 'mr..williams@caseyfreemanandnolan.com'),
(98, 'PHONE', '001-824-642-2933x71421'),
(99, 'EMAIL', 'derek.marshall@thompsonltd.com'),
(99, 'PHONE', '704.655.2948x310'),
(100, 'EMAIL', 'jay.steele@thompsonltd.com'),
(100, 'PHONE', '001-230-804-9311x241'),
(101, 'EMAIL', 'victoria.jones@martinez-riley.com'),
(102, 'EMAIL', 'dr..williams@martinez-riley.com'),
(102, 'PHONE', '7935897596'),
(103, 'EMAIL', 'robert.delacruz@johnsonthomasandgriffin.com'),
(103, 'PHONE', '322-379-0594x7088'),
(104, 'EMAIL', 'steven.cruz@williams-reed.com'),
(104, 'PHONE', '555-497-5114'),
(105, 'EMAIL', 'patricia.smith@williams-reed.com'),
(105, 'PHONE', '(216)322-0112x7560'),
(106, 'EMAIL', 'natalie.williams@williams-reed.com'),
(107, 'EMAIL', 'michael.huff@fordtuckerandbright.com'),
(107, 'PHONE', '(471)766-3146x49047'),
(108, 'EMAIL', 'dustin.cline@dawsonarnoldandwood.com'),
(109, 'EMAIL', 'mary.wilson@dawsonarnoldandwood.com'),
(109, 'PHONE', '(356)675-1577x21169'),
(110, 'EMAIL', 'lisa.arnold@dawsonarnoldandwood.com'),
(110, 'PHONE', '(366)229-8388'),
(111, 'EMAIL', 'cynthia.chavez@larsoncolemanandbush.com'),
(111, 'PHONE', '+1-637-644-9430x81547'),
(112, 'EMAIL', 'beverly.harvey@larsoncolemanandbush.com'),
(112, 'PHONE', '711-576-3571x066'),
(113, 'EMAIL', 'susan.cunningham@larsoncolemanandbush.com'),
(113, 'PHONE', '571-324-5165'),
(114, 'EMAIL', 'mary.gonzales@mcdonaldplc.com'),
(115, 'EMAIL', 'sara.moore@williamsandsons.com'),
(115, 'PHONE', '985.655.9313x4548'),
(116, 'EMAIL', 'david.buchanan@williamsandsons.com'),
(116, 'PHONE', '365.400.1547x443'),
(117, 'EMAIL', 'carl.sanchez@williamsandsons.com'),
(117, 'PHONE', '(977)530-3297'),
(118, 'EMAIL', 'james.garrett@bakerfieldsanderickson.com'),
(118, 'PHONE', '362.307.0401x69508'),
(119, 'EMAIL', 'brittney.roberson@bakerfieldsanderickson.com'),
(120, 'EMAIL', 'timothy.wells@bakerfieldsanderickson.com'),
(120, 'PHONE', '626-960-1598'),
(121, 'EMAIL', 'yolanda.reid@mendezplc.com'),
(121, 'PHONE', '001-664-344-1557x854'),
(122, 'EMAIL', 'thomas.reed@robinson-rogers.com'),
(122, 'PHONE', '001-924-364-9617x9681'),
(123, 'EMAIL', 'christopher.hawkins@roseaustinandreid.com'),
(123, 'PHONE', '323-482-7679x740'),
(124, 'EMAIL', 'bailey.coleman@roseaustinandreid.com'),
(124, 'PHONE', '+1-745-823-9808x838'),
(125, 'EMAIL', 'edward.vaughan@roseaustinandreid.com'),
(125, 'PHONE', '343-305-9559x59355'),
(126, 'EMAIL', 'arthur.suarez@ferguson-cook.com'),
(126, 'PHONE', '975-966-4635x28291'),
(127, 'EMAIL', 'kelly.huber@ferguson-cook.com'),
(127, 'PHONE', '+1-600-606-6156x110'),
(128, 'EMAIL', 'maria.harvey@conradreedandwilliams.com'),
(129, 'EMAIL', 'jack.russo@knightkimandwilson.com'),
(129, 'PHONE', '001-724-732-1200x17029'),
(130, 'EMAIL', 'katherine.carroll@knightkimandwilson.com'),
(131, 'EMAIL', 'abigail.smith@floydcastilloandhaley.com'),
(131, 'PHONE', '694.224.9054x00066'),
(132, 'EMAIL', 'heidi.hess@floydcastilloandhaley.com'),
(132, 'PHONE', '639.866.9289x47190'),
(133, 'EMAIL', 'alison.hoffman@floydcastilloandhaley.com'),
(134, 'EMAIL', 'candice.crawford@hughes-bernard.com'),
(135, 'EMAIL', 'greg.lee@thornton-watts.com'),
(135, 'PHONE', '3489350744'),
(136, 'EMAIL', 'kimberly.gonzalez@jensen-lopez.com'),
(136, 'PHONE', '964-206-5752x57897'),
(137, 'EMAIL', 'brian.edwards@jensen-lopez.com'),
(138, 'EMAIL', 'marcus.hughes@jensen-lopez.com'),
(139, 'EMAIL', 'jennifer.anderson@andrade-brooks.com'),
(139, 'PHONE', '647-697-4829x707'),
(140, 'EMAIL', 'brandon.hicks@gomez-rhodes.com'),
(140, 'PHONE', '360-485-6052'),
(141, 'EMAIL', 'ryan.alvarez@gomez-rhodes.com');

-- Contractor Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('9a745e55-1d1f-436f-8c7b-8c2cabe25aa6', 1, '6506 Sara Island Suite 130', 'Wongstad', 'United Arab Emirates', '15020', 'SHIPPING'),
('e9e24565-7db5-4b9f-a3dc-c02ccfc97877', 2, '725 Hess Meadow', 'Kylefurt', 'Croatia', '99558', 'SHIPPING'),
('1ca4037c-7888-489e-b1ae-400bac464c40', 3, '55691 Mendoza Pike', 'Port Christophermouth', 'Korea', '93080', 'CORPORATE'),
('1754a763-cff7-40b7-9a2d-66398d053186', 3, '74958 Dawn Spurs Suite 666', 'Lake Angelafurt', 'Oman', '88439', 'OTHER'),
('25ce0688-e852-42a6-8833-e8b6a62e2005', 3, '451 Yolanda Loaf', 'South Katherine', 'Aruba', '42828', 'SHIPPING'),
('04ea060c-2fa8-4b1f-a269-ece9c02139bf', 4, '355 Carroll Ports', 'South Sue', 'Palestinian Territory', '80100', 'CORPORATE'),
('17d9641c-52b4-43a7-b494-b20aa3c1e3d1', 5, '89316 Victor Valleys', 'Brendanland', 'Afghanistan', '32604', 'CORPORATE'),
('438aaf69-96ba-461a-8b53-cb6e55df8a74', 6, '6377 Melissa Camp', 'East Charles', 'Luxembourg', '49359', 'BILLING'),
('768a6287-bc2f-40e5-9ecf-59fd7d95e59b', 7, '297 Duncan Cape Apt. 625', 'Wilsonville', 'Romania', '84959', 'SHIPPING'),
('6f17da39-e39b-47ad-ad3c-1b8229dd912b', 8, '81665 Amy Burg', 'Loweryshire', 'Palau', '53656', 'OTHER'),
('928755d9-d095-484d-8455-1a9259e17847', 9, '50160 Andrew Branch', 'Salinaston', 'Iran', '97248', 'OTHER'),
('de2bae12-f155-4f96-af4f-dc65de501249', 9, '27289 Williams Green', 'New Dennis', 'Northern Mariana Islands', '41077', 'CORPORATE'),
('22fcc605-49c6-4545-af88-8efee2595505', 9, '4643 Robert Tunnel', 'Smithfurt', 'Mozambique', '42082', 'SHIPPING'),
('a1a1e5c2-d587-4315-9655-48ff5d26e639', 10, '857 Matthew Trail Suite 988', 'Hernandezbury', 'Indonesia', '88096', 'BILLING'),
('7b22b057-36af-4dc0-84d2-8f3e0d0dca30', 11, '3806 Peter Turnpike Suite 422', 'East Timothy', 'Sudan', '23293', 'CORPORATE'),
('02b81687-f420-4e27-a0be-c3f7d9c6c2e1', 12, '94081 Stephens Turnpike', 'New Tylerburgh', 'Central African Republic', '58304', 'BILLING'),
('b92d0351-e59e-4584-9bfc-69a20f58a227', 13, '123 Kevin Ports', 'Shawfurt', 'Holy See (Vatican City State)', '17480', 'CORPORATE'),
('8d2b8c7a-31d3-4b08-a949-2d397e4927e9', 14, '90377 Harvey Rest', 'Port Samanthastad', 'Dominica', '02568', 'CORPORATE'),
('3d7b2883-7a8c-4532-bc1f-4403c968f3ed', 15, '5847 Kristin Branch', 'Gloriatown', 'Georgia', '90559', 'BILLING'),
('f7c4b632-9e91-41a4-a256-f43b28c8846d', 15, '6773 Richards Brooks Suite 725', 'Port Matthewbury', 'French Guiana', '50696', 'CORPORATE'),
('96f81d0d-c281-474c-aba2-c0d127eaf914', 16, '584 Padilla Extensions', 'Millerberg', 'Bermuda', '86833', 'OTHER'),
('24da9cc3-2eda-41a4-9699-8432fc5b8d91', 17, '24177 Lauren Corner', 'Port Kelly', 'Chile', '66880', 'CORPORATE'),
('4081db10-f12e-4d11-af0c-8185cb8a644a', 17, '272 Davidson Lights', 'Colleenberg', 'Cook Islands', '01282', 'OTHER'),
('1389bdb6-271e-4488-a94e-7e859b3c7a88', 18, '1620 Jason Motorway Suite 924', 'West Thomas', 'Greece', '42657', 'BILLING'),
('09807609-860b-41e3-bd5c-2a7b5a1e3d1d', 18, '268 Andrea Port Suite 045', 'West Mitchell', 'Iraq', '71623', 'CORPORATE'),
('94e9e74e-1d95-49ed-8a7c-91d581b690e4', 19, '9464 Frank Lodge Suite 474', 'Thomasville', 'Sao Tome and Principe', '10616', 'BILLING'),
('3bbc4df7-40cc-42b9-9139-045187150645', 20, '95332 Wilson Union Suite 127', 'Port Daniel', 'New Caledonia', '27599', 'SHIPPING'),
('1e6ca35e-4dcb-4648-ad9e-70ef38837bfc', 21, '19146 Johnson Crossing Apt. 815', 'Medinastad', 'Denmark', '50514', 'SHIPPING'),
('30bfbfb6-165d-4e50-935a-8762f9a35193', 21, '582 Evans Station', 'Port Molly', 'Algeria', '97132', 'OTHER'),
('91f7b659-b236-47a3-841e-8e5d1d980a14', 22, '4493 Carlos Station', 'Duncanmouth', 'Botswana', '34719', 'BILLING'),
('d3187ed6-5ab0-41ef-b9f5-b7cb2b6e4f03', 23, '9348 Alex Estate Suite 692', 'Lake Nathanielport', 'Uganda', '32523', 'CORPORATE'),
('7df6e913-58e4-4388-af23-8bbfce87b287', 23, '778 Holmes Land', 'Edwardsview', 'El Salvador', '15500', 'SHIPPING'),
('00539d3b-c7b2-428a-9af2-b2fd2762cc6d', 24, '1789 Dennis Groves Apt. 525', 'West Michelle', 'British Virgin Islands', '87584', 'CORPORATE'),
('c52e3ed1-5efb-404b-98a2-db74b57fe0fd', 25, '91264 Cynthia Ridges Apt. 159', 'New Deanna', 'Netherlands', '06775', 'BILLING'),
('0f0eab99-2fe1-4f62-9ef6-9cd356dec257', 26, '76965 Gonzalez Gateway', 'East Amandaberg', 'Tuvalu', '27200', 'BILLING'),
('10fb0e72-34f1-4459-8648-50eeea3aeda1', 26, '01769 David Flat', 'North Jennifer', 'Kiribati', '26634', 'SHIPPING'),
('77f16d91-e785-4cec-ae82-eb2dd6172e7e', 27, '421 Jonathan Dam Apt. 837', 'Greeneberg', 'Iceland', '89992', 'OTHER'),
('5ff9c410-a9d0-4168-99d4-cb49da5b1222', 28, '759 Rebecca View', 'Henryfurt', 'Holy See (Vatican City State)', '24747', 'SHIPPING'),
('bb1aa8f9-815a-424d-bb5e-5acce20cfb19', 29, '9859 Craig Center Suite 863', 'Selenaview', 'Seychelles', '97702', 'OTHER'),
('2ddf2037-2738-4d26-9f44-e016586bdbde', 30, '35259 Holmes Shore Suite 888', 'Port Briannamouth', 'Papua New Guinea', '80402', 'CORPORATE'),
('ed3e7fe1-dade-48c7-95eb-ad8c6ca22d5a', 30, '0561 Walker Island Suite 367', 'East Steven', 'Paraguay', '28081', 'OTHER'),
('54acc020-c632-4b60-b21f-1d598959680f', 31, '10318 Desiree Point', 'Willisbury', 'Senegal', '76011', 'OTHER'),
('9193cba8-aa4e-4fd4-915d-ff382c51c13b', 32, '4074 Brittany Summit', 'Crawfordfurt', 'Botswana', '95571', 'BILLING'),
('30bb8721-4ffb-4399-9bef-778a7e3143dc', 32, '6570 White Square Suite 641', 'Jenkinsville', 'Palestinian Territory', '22617', 'OTHER'),
('c1a76ca6-e40e-4e46-9869-eaed52f3a848', 33, '908 Melissa Rapids', 'Dianeburgh', 'Timor-Leste', '72233', 'OTHER'),
('bee801bc-aafe-485d-b5c0-38516d09ebb0', 33, '559 Gilbert Loaf', 'New Stephanie', 'Senegal', '02361', 'SHIPPING'),
('70980594-7f0c-4b03-b9b9-ee3a505eb291', 34, '8430 Charles Centers Apt. 873', 'Leeborough', 'Palestinian Territory', '51717', 'CORPORATE'),
('661a604b-f7f7-4622-a8c4-6dc07698f845', 35, '280 Anderson View Apt. 608', 'Reyesville', 'Cuba', '76595', 'CORPORATE'),
('9b7843aa-3c60-4177-ba7b-1cb563f036ef', 36, '85950 Melendez Parks', 'East Michael', 'Haiti', '04097', 'OTHER'),
('4fa3f564-9658-48aa-ac9d-5dd037c55afc', 36, '99791 Cunningham Overpass', 'Sherichester', 'Saint Lucia', '39164', 'SHIPPING'),
('182ae934-7166-4cdc-8654-83ce599f6ff2', 37, '0923 Margaret Village Apt. 518', 'Port Kelly', 'New Zealand', '50269', 'BILLING'),
('413b85c5-c575-4d76-8d94-fa4cb977a2dd', 37, '8634 Merritt Trafficway Apt. 509', 'Taylorport', 'Saint Kitts and Nevis', '69205', 'OTHER'),
('80292f78-670e-4c4d-9466-30e8c652b7a4', 38, '17194 Steven Haven Apt. 783', 'Penningtonborough', 'Tajikistan', '23265', 'BILLING'),
('5905efd9-1630-42b3-8b3e-dea8268d7fa3', 38, '8835 Ramirez Stravenue Suite 425', 'Brianfort', 'Hong Kong', '59472', 'CORPORATE'),
('ebcc02ba-1201-48c3-8b1d-994ab91c9db9', 39, '0759 Louis Gardens', 'Zacharyside', 'Seychelles', '41591', 'CORPORATE'),
('98da66f5-2d40-457f-b9ff-ec71bbcd061c', 40, '592 Rodgers Ville Suite 144', 'Vegaland', 'Turks and Caicos Islands', '81276', 'CORPORATE'),
('8d9b04db-f74f-4d44-9eb8-4a0449761be3', 41, '252 Jaime Lights Suite 756', 'Sarastad', 'Mexico', '62306', 'SHIPPING'),
('0dadffdd-98ce-4064-9354-e11b94f2a4d4', 42, '02641 Jones Courts Apt. 195', 'East Deborahport', 'Cocos (Keeling) Islands', '09150', 'SHIPPING'),
('e03947b3-46bd-46d7-ba0c-82f1520a3880', 42, '10096 Brandi Ferry Apt. 442', 'Chaseport', 'Egypt', '35385', 'OTHER'),
('d41496b1-6f5b-476d-ab26-b493a5ab6c06', 42, '7173 Robert Lake', 'North Angel', 'Croatia', '39451', 'CORPORATE'),
('12657977-b7a3-47d0-bb2f-9f3f8ffd64fc', 43, '4949 Matthew Fall', 'Howardborough', 'Germany', '44201', 'SHIPPING'),
('6d7ed70e-a069-4429-8168-223aed9c9720', 43, '278 Laura Key', 'East Carlos', 'Italy', '51534', 'OTHER'),
('c30be691-e26e-47a4-91d9-1e9f387d6602', 44, '5253 Eric Orchard', 'New Valerieshire', 'Afghanistan', '71302', 'CORPORATE'),
('e01bdda5-4da9-4f16-8731-d471e8b6a806', 44, '2188 Taylor Forges', 'Jamesland', 'Marshall Islands', '91578', 'OTHER'),
('15856340-b4cf-4d0b-a7cc-17af01fca317', 45, '741 Jackson Tunnel Apt. 877', 'Frenchmouth', 'Bulgaria', '42844', 'BILLING'),
('7c008644-3494-49bc-965b-097675981af9', 45, '4079 Brown Throughway', 'East Donaldton', 'Seychelles', '67300', 'OTHER'),
('acc6e729-b870-474f-82a8-503ffc468be1', 46, '6144 Franco Extensions', 'North Michaelport', 'Comoros', '21278', 'OTHER'),
('c8902f96-054b-4bdd-aeea-381ecfc715f1', 46, '767 Zachary Point', 'Lake Austin', 'Estonia', '71990', 'BILLING'),
('4f526420-e5c8-4ecb-ad3d-137fb4168be9', 47, '0612 Hayden Radial', 'Thomaschester', 'Djibouti', '94662', 'SHIPPING'),
('7e0ef104-d888-437d-9914-f6c977006524', 48, '101 Fowler Inlet Suite 414', 'Port Shane', 'Burkina Faso', '75399', 'BILLING'),
('7ba2c311-ea03-4d94-8f6b-a759eb0ca442', 49, '259 Jennifer Isle Suite 997', 'West Bradleyhaven', 'Jersey', '20308', 'CORPORATE'),
('262875c4-ee79-4684-8e3a-a12fdd893839', 50, '284 Kristin Ford', 'Kellyland', 'Gambia', '33589', 'BILLING');

-- Employee Parties
INSERT INTO party (party_id, name, data, created_at, updated_at) VALUES
(51, 'Jennifer Lynn', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-05-28 11:50:53', '2026-04-24 02:44:20'),
(52, 'Kimberly Hanna', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-09-25 18:29:11', '2026-01-16 07:02:46'),
(53, 'David Brown', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-12-01 06:54:21', '2025-09-30 14:05:37'),
(54, 'Virginia Warner', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-07-16 04:09:44', '2025-10-23 11:45:19'),
(55, 'Debbie Ross', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-12-30 14:35:00', '2026-08-25 20:11:19'),
(56, 'Jennifer Dixon', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-09-30 08:24:08', '2026-02-26 16:26:19'),
(57, 'Denise Rodriguez', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-11-14 12:04:52', '2026-05-14 01:22:17'),
(58, 'Deanna Horn', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2025-05-08 18:00:59', '2026-06-13 05:13:58'),
(59, 'Melody Yoder', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-07-02 17:52:33', '2026-01-17 12:34:27'),
(60, 'Russell Montgomery', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-11-29 13:58:11', '2025-12-14 09:21:25'),
(61, 'Kyle Griffin', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-10-10 09:05:56', '2025-09-14 08:55:00'),
(62, 'Janet Williamson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-05-25 06:25:21', '2025-11-15 19:24:37'),
(63, 'Grant David', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-07-27 15:42:05', '2026-02-04 07:41:08'),
(64, 'Stephanie Harris', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-02-04 12:16:00', '2026-07-06 08:16:10'),
(65, 'Sarah Logan', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-06-01 06:01:58', '2025-11-25 19:49:50'),
(66, 'Gary Williams', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2023-12-14 13:37:45', '2025-11-11 05:47:41'),
(67, 'Judy Scott', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2021-12-24 05:13:03', '2025-10-02 06:31:54'),
(68, 'Joseph Jackson', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-10-31 08:50:30', '2026-07-25 19:35:29'),
(69, 'Anthony Payne', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2024-12-11 06:50:57', '2025-12-06 18:25:16'),
(70, 'Elizabeth Smith', '{"type": "employee", "status": "ACTIVE"}'::jsonb, '2022-10-25 22:58:01', '2026-03-19 11:03:24');

-- Employee Addresses
INSERT INTO address (address_id, party_id, street_address, city, country, postal_code, address_type) VALUES
('481d0c7b-7810-4db3-9aeb-f739528b9a05', 51, '05011 Stephen Roads Suite 004', 'Hortonmouth', 'Samoa', '47352', 'PERSONAL'),
('7b4807e1-bc9b-4289-8802-f50a35832d60', 51, '762 Mary Underpass Suite 348', 'South Rebecca', 'Pakistan', '08229', 'OTHER'),
('0a016e3e-8335-4bb5-b5fc-48d98cae0008', 52, '4277 Alvarado Underpass', 'Youngtown', 'Libyan Arab Jamahiriya', '24420', 'OTHER'),
('7872a887-8394-430b-984c-c1fa4df79efc', 53, '158 Jeff Cove', 'Lopezside', 'Australia', '63524', 'OTHER'),
('63383ed2-9820-48bc-8218-cb6eb9306d8c', 54, '209 Hunter Court', 'Sextonland', 'Belarus', '10884', 'OTHER'),
('7f4fad64-80f1-44a9-a583-f48d49ab9418', 55, '35969 Jones Via', 'Lake Mariaville', 'New Zealand', '27059', 'PERSONAL'),
('073e0f56-a9db-4910-8273-84bc5b218db6', 56, '09370 Andrew Hills', 'West Chad', 'Northern Mariana Islands', '77422', 'PERSONAL'),
('031b90a5-828d-4622-b39c-16ddc14556fb', 57, '2599 Carlson Neck', 'Ericafort', 'Uganda', '72234', 'PERSONAL'),
('966e2cac-7abd-40a4-b15d-964c597af499', 58, '224 Blevins Stream Suite 124', 'Johnnystad', 'Christmas Island', '30861', 'OTHER'),
('895ec736-8226-4039-a965-dc1b6cdc4b65', 58, '27314 Stephanie View', 'Parsonsburgh', 'Kuwait', '17839', 'PERSONAL'),
('1f48fd6c-f1e3-433b-b8cf-57bf7485d46b', 59, '39201 Elizabeth Valley', 'Johnborough', 'Equatorial Guinea', '38460', 'PERSONAL'),
('27726f7c-84c9-409d-9290-5c0b6f41d82c', 59, '280 Jessica Plains', 'North Donaldfurt', 'Niue', '23981', 'OTHER'),
('3d863758-5c99-473d-a3f2-68c4f060672c', 60, '791 Teresa Inlet', 'South Brian', 'Romania', '31332', 'OTHER'),
('cc99dc60-b3f2-4029-bbc0-070eb05c8bb2', 60, '2292 Ross Bypass', 'East Sarahside', 'Congo', '56664', 'PERSONAL'),
('0701c0b9-400a-494e-8f6f-7d03fe8120bc', 61, '625 Patricia Heights', 'Langfurt', 'Latvia', '07888', 'OTHER'),
('caf0500e-225c-49ba-ada5-43661b05f1fa', 61, '8558 Middleton Walks', 'North Elizabethside', 'Antigua and Barbuda', '39799', 'PERSONAL'),
('fd7243e1-fb25-41cc-9612-7e69c55428d4', 62, '582 Brandon Courts Apt. 106', 'Laurafort', 'Singapore', '70247', 'PERSONAL'),
('8183fd28-5fc0-40a2-8a9d-274064e75c4f', 62, '4080 Moore Cliffs', 'Robertsonmouth', 'Namibia', '93246', 'OTHER'),
('66629f1d-ef9c-4ff9-aa23-1cd7e1b14a66', 63, '52005 Rachel River', 'Lake Matthewmouth', 'Zambia', '84478', 'PERSONAL'),
('6aeabefd-847e-49b3-8cdd-877f8c92d262', 64, '08944 Crane Circle Suite 350', 'South Maria', 'Moldova', '29321', 'OTHER'),
('636770cf-57b9-455c-a312-1961520bc3e5', 65, '141 Sanchez Cove', 'New Danielle', 'Sao Tome and Principe', '61579', 'OTHER'),
('26fd9895-0bee-4357-ad44-f5f9e4686fd5', 66, '95093 Erin Port Suite 863', 'Lake Timothyfort', 'Belarus', '28513', 'OTHER'),
('d7d9a524-a439-4f5c-b6a9-84143d83be81', 67, '71737 Taylor Flats', 'Rebeccaberg', 'Aruba', '21701', 'OTHER'),
('f223a9b9-2cae-4091-bbcd-4f0191a7f181', 68, '42056 Tara Green', 'South Tracy', 'Morocco', '82999', 'OTHER'),
('53e515cd-5128-4e43-b08b-39aaa1301a77', 68, '514 Tamara Light', 'Jacobsbury', 'Chile', '74106', 'PERSONAL'),
('2d02a48f-61d1-4735-902a-73349d630f56', 69, '9113 David Keys Suite 660', 'Travisberg', 'Rwanda', '84735', 'OTHER'),
('bba1852e-6ff4-4eaa-8015-43abc4fa09ba', 69, '42560 Casey Road', 'Lake Ronnie', 'Denmark', '54795', 'PERSONAL'),
('d195214c-8f3f-4946-a981-f761cf4b4012', 70, '408 Gray Groves Suite 089', 'West Danielshire', 'Belgium', '93643', 'OTHER');

-- Employee Contacts
INSERT INTO party_contact (party_id, type, details) VALUES
(51, 'EMAIL', 'tayloramy@example.net'),
(51, 'PHONE', '(571)784-8459x4642'),
(52, 'EMAIL', 'herrerastephanie@example.com'),
(52, 'PHONE', '+1-422-557-6627x368'),
(53, 'EMAIL', 'cynthia96@example.net'),
(53, 'PHONE', '001-974-955-0640x92529'),
(54, 'EMAIL', 'ginawalter@example.org'),
(54, 'PHONE', '390-646-8864'),
(55, 'EMAIL', 'matthew00@example.org'),
(55, 'PHONE', '001-795-828-6503'),
(56, 'EMAIL', 'sgarcia@example.com'),
(56, 'PHONE', '001-349-524-6467x24806'),
(57, 'EMAIL', 'michael33@example.net'),
(57, 'PHONE', '+1-993-364-1739x26642'),
(58, 'EMAIL', 'gerald65@example.net'),
(58, 'PHONE', '5619351024'),
(59, 'EMAIL', 'vcollins@example.com'),
(59, 'PHONE', '(300)908-3090x57980'),
(60, 'EMAIL', 'ruizsara@example.org'),
(60, 'PHONE', '464.696.4950x9352'),
(61, 'EMAIL', 'lanemelissa@example.net'),
(61, 'PHONE', '(662)657-2252x652'),
(62, 'EMAIL', 'brangel@example.org'),
(62, 'PHONE', '+1-362-835-4634x6815'),
(63, 'EMAIL', 'kathleen41@example.com'),
(63, 'PHONE', '4434433095'),
(64, 'EMAIL', 'sandrasmith@example.com'),
(64, 'PHONE', '(899)478-8519'),
(65, 'EMAIL', 'sarah17@example.com'),
(65, 'PHONE', '+1-593-303-1282x64734'),
(66, 'EMAIL', 'romeromichael@example.com'),
(66, 'PHONE', '+1-300-332-9945x390'),
(67, 'EMAIL', 'oestrada@example.org'),
(67, 'PHONE', '(772)455-5320x8674'),
(68, 'EMAIL', 'jacob50@example.com'),
(68, 'PHONE', '(670)623-3488'),
(69, 'EMAIL', 'daniellephillips@example.com'),
(69, 'PHONE', '(880)926-7467x54857'),
(70, 'EMAIL', 'joseflores@example.org'),
(70, 'PHONE', '001-959-468-9546x15104');

-- Party Roles
INSERT INTO party_role (party_id, role_id, assigned_date) VALUES
(51, 5, '2025-11-15 07:16:46'),
(52, 4, '2025-06-29 12:18:33'),
(53, 5, '2025-11-17 12:51:00'),
(54, 5, '2024-10-25 03:27:36'),
(55, 5, '2023-02-07 01:38:24'),
(55, 3, '2026-06-17 23:09:37'),
(56, 4, '2024-09-18 23:09:32'),
(57, 5, '2025-05-09 05:44:34'),
(57, 3, '2024-12-26 07:29:31'),
(58, 3, '2025-09-06 22:02:25'),
(58, 5, '2025-09-30 10:37:11'),
(59, 5, '2026-05-30 10:36:09'),
(60, 5, '2026-02-07 09:04:09'),
(61, 3, '2024-06-05 23:10:04'),
(62, 5, '2026-05-21 14:46:49'),
(63, 5, '2022-10-19 18:47:59'),
(63, 3, '2023-04-03 12:11:23'),
(64, 5, '2025-12-03 13:22:21'),
(65, 5, '2024-01-04 21:16:34'),
(65, 4, '2024-08-03 05:56:53'),
(66, 5, '2023-12-18 23:17:22'),
(67, 3, '2025-12-31 01:55:23'),
(68, 4, '2026-02-03 18:53:48'),
(69, 5, '2026-03-05 08:24:45'),
(70, 3, '2025-01-22 13:28:08'),
(70, 5, '2026-05-18 06:06:17');

-- Employee Warehouses
INSERT INTO employee_warehouse (party_id, warehouse_id, assigned_from, assigned_until) VALUES
(51, 1, '2023-05-28 11:50:53', NULL),
(52, 1, '2024-09-25 18:29:11', NULL),
(53, 1, '2022-12-01 06:54:21', NULL),
(54, 1, '2024-07-16 04:09:44', NULL),
(55, 1, '2021-12-30 14:35:00', NULL),
(56, 1, '2023-09-30 08:24:08', NULL),
(57, 1, '2024-11-14 12:04:52', NULL),
(58, 1, '2025-05-08 18:00:59', NULL),
(59, 1, '2024-07-02 17:52:33', NULL),
(60, 1, '2024-11-29 13:58:11', NULL),
(61, 1, '2023-10-10 09:05:56', NULL),
(62, 1, '2024-05-25 06:25:21', NULL),
(63, 1, '2022-07-27 15:42:05', NULL),
(64, 1, '2024-02-04 12:16:00', NULL),
(65, 1, '2022-06-01 06:01:58', NULL),
(66, 1, '2023-12-14 13:37:45', NULL),
(67, 1, '2021-12-24 05:13:03', NULL),
(68, 1, '2024-10-31 08:50:30', NULL),
(69, 1, '2024-12-11 06:50:57', NULL),
(70, 1, '2022-10-25 22:58:01', NULL);

-- Cargo Event Types
INSERT INTO cargo_event_type (event_type_id, name, description) VALUES
(1, 'RECEIVED', 'Cargo received at warehouse'),
(2, 'MOVED', 'Cargo moved to another shelf'),
(3, 'DISPATCHED', 'Cargo dispatched from warehouse'),
(4, 'DAMAGED', 'Cargo found damaged'),
(5, 'LOST', 'Cargo missing or lost'),
(6, 'CONTRACTOR_CONTACT', 'Contact with contractor regarding storage'),
(7, 'QUALITY_ISSUE', 'Quality-related issue reported'),
(8, 'SAFETY_INCIDENT', 'Safety or accident incident reported');

-- Zones
INSERT INTO zone (zone_id, warehouse_id, code, name, description) VALUES
(1, 1, 'BULK', 'Bulk Storage Area', 'Area for storing large quantities of goods, usually on pallets.'),
(2, 1, 'RECV', 'Receiving Area', 'Zone designated for unloading and inspecting incoming goods.'),
(3, 1, 'PICK', 'Picking Area', 'Zone where items are picked to fulfill orders.'),
(4, 1, 'PACK', 'Packing Area', 'Area for packing picked items and preparing them for shipment.'),
(5, 1, 'SHIP', 'Shipping Area', 'Zone for staging and loading outbound shipments.'),
(6, 1, 'RET', 'Returns Area', 'Designated space for processing returned goods.'),
(7, 1, 'QC', 'Quarantine/Inspection Area', 'Area for holding goods pending inspection or quality checks.');

-- Aisles
INSERT INTO aisle (aisle_id, zone_id, label, width, width_unit) VALUES
(1, 1, 'A01', 250, 'cm'),
(2, 1, 'A02', 250, 'cm'),
(3, 1, 'A03', 350, 'cm'),
(4, 1, 'A04', 200, 'cm'),
(5, 1, 'A05', 200, 'cm'),
(6, 1, 'A06', 200, 'cm'),
(7, 1, 'A07', 300, 'cm');

-- Racks
INSERT INTO rack (rack_id, aisle_id, label, max_height, height_unit) VALUES
(1, 1, 'R001', 500, 'cm'),
(2, 2, 'R002', 500, 'cm'),
(3, 3, 'R003', 350, 'cm'),
(4, 4, 'R004', 450, 'cm'),
(5, 5, 'R005', 500, 'cm'),
(6, 6, 'R006', 450, 'cm'),
(7, 7, 'R007', 450, 'cm'),
(8, 1, 'R008', 500, 'cm'),
(9, 2, 'R009', 400, 'cm'),
(10, 3, 'R010', 450, 'cm');

-- Shelves
INSERT INTO shelf (shelf_id, rack_id, level, max_weight, max_volume) VALUES
(1, 1, '1', 698, 6),
(2, 1, '2', 1133, 12),
(3, 2, '1', 824, 5),
(4, 2, '2', 993, 7),
(5, 3, '1', 832, 10),
(6, 3, '2', 772, 14),
(7, 4, '1', 1156, 15),
(8, 4, '2', 687, 14),
(9, 5, '1', 1089, 8),
(10, 5, '2', 906, 5),
(11, 6, '1', 1107, 5),
(12, 6, '2', 967, 7),
(13, 7, '1', 846, 15),
(14, 7, '2', 727, 13),
(15, 8, '1', 949, 15);

-- Storage Requests
INSERT INTO storage_request (request_id, warehouse_id, issuing_party_id, requested_entry_date, requested_exit_date, status, decisive_party_id, decision_date) VALUES
(1, 1, 21, '2026-08-12 10:04:27', '2026-08-19 10:04:27', 'REJECTED', 66, '2026-08-10 10:04:27'),
(2, 1, 98, '2026-08-17 07:19:51', '2026-09-07 07:19:51', 'ACCEPTED', 70, '2026-08-15 07:19:51'),
(3, 1, 36, '2026-08-16 14:13:15', '2026-09-08 14:13:15', 'REJECTED', 69, '2026-08-14 14:13:15'),
(4, 1, 125, '2026-09-01 12:33:29', '2026-09-25 12:33:29', 'REJECTED', 62, '2026-08-29 12:33:29'),
(5, 1, 108, '2026-08-23 19:12:20', '2026-08-30 19:12:20', 'PENDING', NULL, NULL),
(6, 1, 8, '2026-07-28 23:03:51', '2026-08-07 23:03:51', 'ACCEPTED', 67, '2026-07-26 23:03:51'),
(7, 1, 77, '2026-08-31 23:15:02', '2026-09-20 23:15:02', 'REJECTED', 60, '2026-08-30 23:15:02'),
(8, 1, 137, '2026-07-29 03:42:10', '2026-08-22 03:42:10', 'REJECTED', 58, '2026-07-26 03:42:10'),
(9, 1, 38, '2026-08-21 08:33:47', '2026-09-17 08:33:47', 'PENDING', NULL, NULL),
(10, 1, 121, '2026-09-16 12:33:50', '2026-09-22 12:33:50', 'ACCEPTED', 65, '2026-09-15 12:33:50'),
(11, 1, 112, '2026-08-15 11:09:06', '2026-09-04 11:09:06', 'PENDING', NULL, NULL),
(12, 1, 107, '2026-08-19 19:04:58', '2026-09-09 19:04:58', 'PENDING', NULL, NULL),
(13, 1, 129, '2026-08-16 06:44:00', '2026-09-13 06:44:00', 'PENDING', NULL, NULL),
(14, 1, 85, '2026-08-13 13:52:26', '2026-09-09 13:52:26', 'ACCEPTED', 65, '2026-08-12 13:52:26'),
(15, 1, 74, '2026-09-17 23:40:51', '2026-10-12 23:40:51', 'ACCEPTED', 69, '2026-09-16 23:40:51'),
(16, 1, 93, '2026-08-25 16:03:07', '2026-09-02 16:03:07', 'REJECTED', NULL, '2026-08-26 16:03:07'),
(17, 1, 41, '2026-09-15 23:43:40', '2026-09-27 23:43:40', 'PENDING', NULL, NULL),
(18, 1, 13, '2026-09-20 18:32:56', '2026-10-18 18:32:56', 'PENDING', NULL, NULL),
(19, 1, 35, '2026-08-06 22:29:21', '2026-09-02 22:29:21', 'ACCEPTED', 53, '2026-08-02 22:29:21'),
(20, 1, 94, '2026-08-21 08:04:55', '2026-09-19 08:04:55', 'REJECTED', NULL, '2026-08-22 08:04:55'),
(21, 1, 118, '2026-08-26 19:45:12', '2026-09-09 19:45:12', 'REJECTED', NULL, '2026-08-28 19:45:12'),
(22, 1, 50, '2026-08-21 08:35:52', '2026-08-29 08:35:52', 'ACCEPTED', 70, '2026-08-20 08:35:52'),
(23, 1, 91, '2026-08-09 22:55:33', '2026-09-01 22:55:33', 'REJECTED', 60, '2026-08-08 22:55:33'),
(24, 1, 105, '2026-08-10 14:23:13', '2026-08-16 14:23:13', 'PENDING', NULL, NULL),
(25, 1, 109, '2026-08-03 20:32:12', '2026-08-20 20:32:12', 'PENDING', NULL, NULL),
(26, 1, 133, '2026-08-27 01:39:21', '2026-09-07 01:39:21', 'ACCEPTED', 67, '2026-08-23 01:39:21'),
(27, 1, 99, '2026-09-04 09:30:01', '2026-09-23 09:30:01', 'ACCEPTED', 57, '2026-08-30 09:30:01'),
(28, 1, 17, '2026-09-10 11:59:40', '2026-09-15 11:59:40', 'PENDING', NULL, NULL),
(29, 1, 125, '2026-08-24 21:15:23', '2026-08-30 21:15:23', 'ACCEPTED', 61, '2026-08-19 21:15:23'),
(30, 1, 34, '2026-09-04 14:37:49', '2026-09-11 14:37:49', 'PENDING', NULL, NULL),
(31, 1, 44, '2026-08-29 08:23:22', '2026-09-12 08:23:22', 'ACCEPTED', 63, '2026-08-28 08:23:22'),
(32, 1, 47, '2026-09-02 09:09:06', '2026-09-12 09:09:06', 'ACCEPTED', 51, '2026-09-01 09:09:06'),
(33, 1, 90, '2026-08-09 16:37:46', '2026-09-04 16:37:46', 'REJECTED', 64, '2026-08-07 16:37:46'),
(34, 1, 81, '2026-08-18 13:17:46', '2026-09-14 13:17:46', 'ACCEPTED', 56, '2026-08-13 13:17:46'),
(35, 1, 4, '2026-07-30 00:32:57', '2026-08-07 00:32:57', 'ACCEPTED', 60, '2026-07-28 00:32:57'),
(36, 1, 86, '2026-09-23 23:53:19', '2026-10-22 23:53:19', 'ACCEPTED', 52, '2026-09-21 23:53:19'),
(37, 1, 7, '2026-09-16 11:10:32', '2026-10-11 11:10:32', 'ACCEPTED', 60, '2026-09-11 11:10:32'),
(38, 1, 92, '2026-08-14 10:03:14', '2026-09-06 10:03:14', 'PENDING', NULL, NULL),
(39, 1, 135, '2026-09-23 06:09:09', '2026-10-06 06:09:09', 'REJECTED', 52, '2026-09-21 06:09:09'),
(40, 1, 22, '2026-09-19 14:32:04', '2026-10-10 14:32:04', 'REJECTED', 69, '2026-09-16 14:32:04'),
(41, 1, 77, '2026-09-07 13:16:39', '2026-09-25 13:16:39', 'PENDING', NULL, NULL),
(42, 1, 90, '2026-09-08 21:47:08', '2026-10-01 21:47:08', 'PENDING', NULL, NULL),
(43, 1, 115, '2026-09-14 09:42:52', '2026-10-14 09:42:52', 'REJECTED', 55, '2026-09-12 09:42:52'),
(44, 1, 47, '2026-08-28 09:42:45', '2026-09-13 09:42:45', 'REJECTED', NULL, '2026-08-29 09:42:45'),
(45, 1, 12, '2026-08-12 03:46:46', '2026-09-11 03:46:46', 'PENDING', NULL, NULL),
(46, 1, 140, '2026-08-13 06:27:54', '2026-09-09 06:27:54', 'PENDING', NULL, NULL),
(47, 1, 19, '2026-08-10 02:05:57', '2026-08-29 02:05:57', 'PENDING', NULL, NULL),
(48, 1, 4, '2026-09-08 22:13:58', '2026-10-07 22:13:58', 'REJECTED', 69, '2026-09-06 22:13:58'),
(49, 1, 94, '2026-09-15 20:15:57', '2026-10-06 20:15:57', 'PENDING', NULL, NULL),
(50, 1, 28, '2026-09-25 15:23:18', '2026-10-15 15:23:18', 'PENDING', NULL, NULL),
(51, 1, 12, '2026-09-22 03:51:27', '2026-10-04 03:51:27', 'ACCEPTED', 69, '2026-09-17 03:51:27'),
(52, 1, 47, '2026-08-03 05:17:44', '2026-08-29 05:17:44', 'PENDING', NULL, NULL),
(53, 1, 40, '2026-08-06 07:17:03', '2026-08-20 07:17:03', 'ACCEPTED', 55, '2026-08-01 07:17:03'),
(54, 1, 136, '2026-09-21 14:13:42', '2026-09-26 14:13:42', 'REJECTED', 61, '2026-09-20 14:13:42'),
(55, 1, 137, '2026-08-18 06:53:18', '2026-09-05 06:53:18', 'PENDING', NULL, NULL),
(56, 1, 98, '2026-08-07 11:10:47', '2026-08-24 11:10:47', 'PENDING', NULL, NULL),
(57, 1, 77, '2026-09-22 08:46:12', '2026-10-10 08:46:12', 'PENDING', NULL, NULL),
(58, 1, 33, '2026-09-26 11:19:48', '2026-10-14 11:19:48', 'ACCEPTED', 54, '2026-09-25 11:19:48'),
(59, 1, 89, '2026-08-16 19:41:24', '2026-08-28 19:41:24', 'PENDING', NULL, NULL),
(60, 1, 76, '2026-09-08 11:38:31', '2026-09-16 11:38:31', 'REJECTED', 61, '2026-09-06 11:38:31'),
(61, 1, 6, '2026-09-02 20:46:43', '2026-09-14 20:46:43', 'REJECTED', NULL, '2026-09-03 20:46:43'),
(62, 1, 41, '2026-08-22 07:50:31', '2026-09-14 07:50:31', 'ACCEPTED', 66, '2026-08-18 07:50:31'),
(63, 1, 13, '2026-09-18 17:17:25', '2026-10-10 17:17:25', 'PENDING', NULL, NULL),
(64, 1, 97, '2026-08-14 08:35:01', '2026-09-02 08:35:01', 'REJECTED', 56, '2026-08-13 08:35:01'),
(65, 1, 130, '2026-08-16 03:01:37', '2026-09-07 03:01:37', 'REJECTED', 68, '2026-08-13 03:01:37'),
(66, 1, 35, '2026-08-28 03:40:22', '2026-09-15 03:40:22', 'REJECTED', 64, '2026-08-25 03:40:22'),
(67, 1, 20, '2026-08-23 15:08:30', '2026-09-08 15:08:30', 'ACCEPTED', 61, '2026-08-20 15:08:30'),
(68, 1, 100, '2026-09-07 10:40:55', '2026-09-17 10:40:55', 'ACCEPTED', 54, '2026-09-04 10:40:55'),
(69, 1, 42, '2026-08-21 16:53:54', '2026-09-12 16:53:54', 'ACCEPTED', 65, '2026-08-19 16:53:54'),
(70, 1, 25, '2026-08-30 22:24:17', '2026-09-14 22:24:17', 'ACCEPTED', 61, '2026-08-26 22:24:17'),
(71, 1, 23, '2026-08-20 18:50:18', '2026-09-13 18:50:18', 'REJECTED', 66, '2026-08-19 18:50:18'),
(72, 1, 40, '2026-09-22 10:36:01', '2026-10-04 10:36:01', 'PENDING', NULL, NULL),
(73, 1, 137, '2026-09-05 20:24:05', '2026-09-28 20:24:05', 'PENDING', NULL, NULL),
(74, 1, 2, '2026-08-29 01:43:19', '2026-09-25 01:43:19', 'REJECTED', 67, '2026-08-28 01:43:19'),
(75, 1, 127, '2026-09-15 15:22:26', '2026-09-26 15:22:26', 'PENDING', NULL, NULL),
(76, 1, 90, '2026-09-17 13:23:23', '2026-09-26 13:23:23', 'ACCEPTED', 54, '2026-09-15 13:23:23'),
(77, 1, 28, '2026-09-06 16:50:37', '2026-09-13 16:50:37', 'ACCEPTED', 53, '2026-09-02 16:50:37'),
(78, 1, 48, '2026-09-06 00:19:52', '2026-09-28 00:19:52', 'PENDING', NULL, NULL),
(79, 1, 14, '2026-09-07 04:09:34', '2026-09-14 04:09:34', 'PENDING', NULL, NULL),
(80, 1, 113, '2026-09-04 01:31:59', '2026-09-18 01:31:59', 'ACCEPTED', 52, '2026-09-01 01:31:59'),
(81, 1, 111, '2026-08-05 17:15:30', '2026-08-17 17:15:30', 'ACCEPTED', 56, '2026-08-03 17:15:30'),
(82, 1, 94, '2026-09-21 13:24:55', '2026-09-27 13:24:55', 'PENDING', NULL, NULL),
(83, 1, 39, '2026-08-07 15:28:31', '2026-08-24 15:28:31', 'REJECTED', NULL, '2026-08-07 15:28:31'),
(84, 1, 110, '2026-09-14 08:39:45', '2026-09-30 08:39:45', 'REJECTED', 67, '2026-09-12 08:39:45'),
(85, 1, 50, '2026-08-04 19:10:26', '2026-08-09 19:10:26', 'REJECTED', NULL, '2026-08-04 19:10:26'),
(86, 1, 102, '2026-09-23 04:44:50', '2026-10-05 04:44:50', 'REJECTED', NULL, '2026-09-24 04:44:50'),
(87, 1, 74, '2026-08-25 19:11:33', '2026-09-16 19:11:33', 'ACCEPTED', 52, '2026-08-23 19:11:33'),
(88, 1, 9, '2026-07-31 06:02:27', '2026-08-16 06:02:27', 'PENDING', NULL, NULL),
(89, 1, 110, '2026-09-12 17:05:04', '2026-10-02 17:05:04', 'PENDING', NULL, NULL),
(90, 1, 111, '2026-08-13 17:00:26', '2026-08-25 17:00:26', 'REJECTED', NULL, '2026-08-15 17:00:26'),
(91, 1, 92, '2026-08-06 04:58:56', '2026-08-11 04:58:56', 'ACCEPTED', 68, '2026-08-05 04:58:56'),
(92, 1, 113, '2026-09-09 23:06:00', '2026-09-17 23:06:00', 'PENDING', NULL, NULL),
(93, 1, 113, '2026-08-19 14:15:40', '2026-09-07 14:15:40', 'REJECTED', 54, '2026-08-16 14:15:40'),
(94, 1, 105, '2026-08-06 10:45:58', '2026-08-16 10:45:58', 'REJECTED', 55, '2026-08-03 10:45:58'),
(95, 1, 46, '2026-09-10 02:36:05', '2026-09-21 02:36:05', 'PENDING', NULL, NULL),
(96, 1, 9, '2026-09-21 05:19:52', '2026-10-19 05:19:52', 'REJECTED', NULL, '2026-09-23 05:19:52'),
(97, 1, 140, '2026-09-11 17:44:48', '2026-09-20 17:44:48', 'REJECTED', 58, '2026-09-08 17:44:48'),
(98, 1, 46, '2026-09-21 16:28:13', '2026-10-04 16:28:13', 'REJECTED', 67, '2026-09-18 16:28:13'),
(99, 1, 84, '2026-07-28 14:53:15', '2026-08-26 14:53:15', 'REJECTED', NULL, '2026-07-28 14:53:15'),
(100, 1, 86, '2026-09-04 00:39:54', '2026-09-22 00:39:54', 'REJECTED', NULL, '2026-09-05 00:39:54'),
(101, 1, 19, '2026-08-29 15:26:06', '2026-09-13 15:26:06', 'ACCEPTED', 64, '2026-08-25 15:26:06'),
(102, 1, 13, '2026-08-07 22:53:31', '2026-08-16 22:53:31', 'PENDING', NULL, NULL),
(103, 1, 40, '2026-08-27 04:06:16', '2026-09-21 04:06:16', 'REJECTED', 56, '2026-08-24 04:06:16'),
(104, 1, 49, '2026-08-01 14:49:31', '2026-08-25 14:49:31', 'REJECTED', NULL, '2026-08-02 14:49:31'),
(105, 1, 72, '2026-09-08 00:58:58', '2026-10-01 00:58:58', 'REJECTED', NULL, '2026-09-09 00:58:58'),
(106, 1, 31, '2026-07-31 05:41:55', '2026-08-10 05:41:55', 'ACCEPTED', 61, '2026-07-30 05:41:55'),
(107, 1, 124, '2026-08-13 22:55:11', '2026-09-07 22:55:11', 'ACCEPTED', 70, '2026-08-12 22:55:11'),
(108, 1, 87, '2026-08-13 23:30:12', '2026-09-03 23:30:12', 'REJECTED', 61, '2026-08-12 23:30:12'),
(109, 1, 30, '2026-09-13 15:37:56', '2026-09-30 15:37:56', 'REJECTED', 51, '2026-09-10 15:37:56'),
(110, 1, 78, '2026-08-02 10:09:58', '2026-08-13 10:09:58', 'ACCEPTED', 59, '2026-08-01 10:09:58'),
(111, 1, 82, '2026-08-06 07:16:33', '2026-08-21 07:16:33', 'ACCEPTED', 60, '2026-08-04 07:16:33'),
(112, 1, 102, '2026-09-24 02:28:21', '2026-10-21 02:28:21', 'ACCEPTED', 66, '2026-09-19 02:28:21'),
(113, 1, 124, '2026-08-06 00:44:37', '2026-08-23 00:44:37', 'ACCEPTED', 64, '2026-08-03 00:44:37'),
(114, 1, 72, '2026-07-30 23:35:56', '2026-08-09 23:35:56', 'PENDING', NULL, NULL),
(115, 1, 129, '2026-07-30 21:27:40', '2026-08-28 21:27:40', 'ACCEPTED', 55, '2026-07-29 21:27:40'),
(116, 1, 138, '2026-09-11 03:22:11', '2026-09-22 03:22:11', 'ACCEPTED', 61, '2026-09-09 03:22:11'),
(117, 1, 125, '2026-08-09 16:25:51', '2026-09-06 16:25:51', 'PENDING', NULL, NULL),
(118, 1, 101, '2026-08-18 16:54:43', '2026-08-31 16:54:43', 'PENDING', NULL, NULL),
(119, 1, 120, '2026-09-02 03:09:59', '2026-09-14 03:09:59', 'REJECTED', 70, '2026-08-31 03:09:59'),
(120, 1, 103, '2026-08-20 15:49:15', '2026-09-19 15:49:15', 'PENDING', NULL, NULL),
(121, 1, 26, '2026-08-05 17:32:05', '2026-08-25 17:32:05', 'PENDING', NULL, NULL),
(122, 1, 80, '2026-09-17 05:02:19', '2026-09-27 05:02:19', 'REJECTED', 58, '2026-09-14 05:02:19'),
(123, 1, 118, '2026-08-04 18:42:07', '2026-08-26 18:42:07', 'PENDING', NULL, NULL),
(124, 1, 38, '2026-09-04 13:57:34', '2026-09-28 13:57:34', 'PENDING', NULL, NULL),
(125, 1, 11, '2026-09-22 01:58:31', '2026-10-11 01:58:31', 'ACCEPTED', 70, '2026-09-20 01:58:31'),
(126, 1, 29, '2026-09-11 06:55:34', '2026-10-11 06:55:34', 'ACCEPTED', 62, '2026-09-09 06:55:34'),
(127, 1, 118, '2026-08-15 05:47:41', '2026-09-14 05:47:41', 'PENDING', NULL, NULL),
(128, 1, 125, '2026-07-31 11:02:25', '2026-08-15 11:02:25', 'PENDING', NULL, NULL),
(129, 1, 89, '2026-08-31 04:34:03', '2026-09-18 04:34:03', 'REJECTED', NULL, '2026-08-31 04:34:03'),
(130, 1, 113, '2026-09-07 09:49:01', '2026-09-29 09:49:01', 'ACCEPTED', 67, '2026-09-05 09:49:01'),
(131, 1, 131, '2026-08-24 11:30:55', '2026-09-07 11:30:55', 'ACCEPTED', 62, '2026-08-21 11:30:55'),
(132, 1, 25, '2026-08-18 01:44:58', '2026-09-13 01:44:58', 'ACCEPTED', 65, '2026-08-16 01:44:58'),
(133, 1, 125, '2026-08-20 09:13:23', '2026-09-16 09:13:23', 'REJECTED', 63, '2026-08-19 09:13:23'),
(134, 1, 43, '2026-08-04 05:14:54', '2026-08-26 05:14:54', 'REJECTED', NULL, '2026-08-06 05:14:54'),
(135, 1, 36, '2026-09-05 14:58:31', '2026-09-23 14:58:31', 'ACCEPTED', 63, '2026-08-31 14:58:31'),
(136, 1, 12, '2026-09-23 11:56:51', '2026-10-11 11:56:51', 'REJECTED', NULL, '2026-09-23 11:56:51'),
(137, 1, 76, '2026-09-15 19:20:49', '2026-09-25 19:20:49', 'ACCEPTED', 61, '2026-09-12 19:20:49'),
(138, 1, 48, '2026-09-07 15:51:43', '2026-09-19 15:51:43', 'REJECTED', 65, '2026-09-05 15:51:43'),
(139, 1, 137, '2026-09-16 15:15:39', '2026-10-14 15:15:39', 'REJECTED', 66, '2026-09-13 15:15:39'),
(140, 1, 8, '2026-08-23 04:22:38', '2026-09-21 04:22:38', 'PENDING', NULL, NULL),
(141, 1, 133, '2026-08-11 22:30:04', '2026-08-24 22:30:04', 'ACCEPTED', 52, '2026-08-07 22:30:04'),
(142, 1, 112, '2026-08-08 21:00:23', '2026-08-13 21:00:23', 'PENDING', NULL, NULL),
(143, 1, 3, '2026-07-30 17:05:00', '2026-08-23 17:05:00', 'ACCEPTED', 67, '2026-07-29 17:05:00'),
(144, 1, 130, '2026-09-09 07:54:09', '2026-09-27 07:54:09', 'PENDING', NULL, NULL),
(145, 1, 15, '2026-08-26 13:47:15', '2026-09-09 13:47:15', 'REJECTED', NULL, '2026-08-26 13:47:15'),
(146, 1, 6, '2026-08-06 19:05:14', '2026-08-29 19:05:14', 'REJECTED', 66, '2026-08-03 19:05:14'),
(147, 1, 102, '2026-08-29 01:23:58', '2026-09-10 01:23:58', 'REJECTED', NULL, '2026-08-29 01:23:58'),
(148, 1, 72, '2026-08-11 04:11:51', '2026-08-17 04:11:51', 'REJECTED', 54, '2026-08-10 04:11:51'),
(149, 1, 115, '2026-09-13 01:38:37', '2026-10-11 01:38:37', 'REJECTED', 57, '2026-09-10 01:38:37'),
(150, 1, 101, '2026-08-08 18:22:25', '2026-09-04 18:22:25', 'ACCEPTED', 59, '2026-08-04 18:22:25'),
(151, 1, 114, '2026-09-10 17:44:42', '2026-10-06 17:44:42', 'ACCEPTED', 61, '2026-09-08 17:44:42'),
(152, 1, 74, '2026-08-28 21:47:38', '2026-09-16 21:47:38', 'ACCEPTED', 66, '2026-08-27 21:47:38'),
(153, 1, 17, '2026-08-05 22:41:47', '2026-08-13 22:41:47', 'REJECTED', 57, '2026-08-02 22:41:47'),
(154, 1, 84, '2026-09-08 11:48:16', '2026-10-05 11:48:16', 'REJECTED', 57, '2026-09-05 11:48:16'),
(155, 1, 26, '2026-08-01 04:57:46', '2026-08-14 04:57:46', 'PENDING', NULL, NULL),
(156, 1, 114, '2026-08-14 20:31:50', '2026-09-04 20:31:50', 'ACCEPTED', 64, '2026-08-10 20:31:50'),
(157, 1, 137, '2026-09-02 03:04:17', '2026-09-15 03:04:17', 'ACCEPTED', 69, '2026-08-28 03:04:17'),
(158, 1, 7, '2026-09-23 21:58:56', '2026-10-20 21:58:56', 'PENDING', NULL, NULL),
(159, 1, 22, '2026-09-16 21:06:48', '2026-10-10 21:06:48', 'PENDING', NULL, NULL),
(160, 1, 14, '2026-07-30 23:24:00', '2026-08-27 23:24:00', 'PENDING', NULL, NULL),
(161, 1, 26, '2026-08-23 21:11:04', '2026-09-21 21:11:04', 'PENDING', NULL, NULL),
(162, 1, 48, '2026-08-15 08:33:01', '2026-09-07 08:33:01', 'ACCEPTED', 70, '2026-08-11 08:33:01'),
(163, 1, 35, '2026-09-02 05:23:13', '2026-09-17 05:23:13', 'REJECTED', NULL, '2026-09-04 05:23:13'),
(164, 1, 30, '2026-08-15 09:37:47', '2026-08-20 09:37:47', 'PENDING', NULL, NULL),
(165, 1, 108, '2026-09-17 06:27:16', '2026-10-13 06:27:16', 'REJECTED', 64, '2026-09-15 06:27:16'),
(166, 1, 109, '2026-09-01 11:57:17', '2026-09-12 11:57:17', 'PENDING', NULL, NULL),
(167, 1, 137, '2026-08-04 16:18:28', '2026-08-23 16:18:28', 'PENDING', NULL, NULL),
(168, 1, 42, '2026-09-11 03:47:12', '2026-09-28 03:47:12', 'REJECTED', 61, '2026-09-10 03:47:12'),
(169, 1, 11, '2026-09-02 00:42:54', '2026-09-09 00:42:54', 'PENDING', NULL, NULL),
(170, 1, 136, '2026-08-03 00:13:52', '2026-08-12 00:13:52', 'ACCEPTED', 59, '2026-08-02 00:13:52'),
(171, 1, 10, '2026-09-16 11:00:50', '2026-10-06 11:00:50', 'REJECTED', 56, '2026-09-15 11:00:50'),
(172, 1, 115, '2026-09-18 08:45:35', '2026-09-28 08:45:35', 'REJECTED', NULL, '2026-09-20 08:45:35'),
(173, 1, 42, '2026-08-17 18:08:21', '2026-09-06 18:08:21', 'REJECTED', 56, '2026-08-15 18:08:21'),
(174, 1, 17, '2026-09-09 14:47:26', '2026-09-27 14:47:26', 'PENDING', NULL, NULL),
(175, 1, 133, '2026-09-14 10:04:11', '2026-09-22 10:04:11', 'REJECTED', NULL, '2026-09-16 10:04:11'),
(176, 1, 92, '2026-08-01 03:31:01', '2026-08-09 03:31:01', 'ACCEPTED', 69, '2026-07-31 03:31:01'),
(177, 1, 71, '2026-08-16 08:17:52', '2026-08-25 08:17:52', 'ACCEPTED', 58, '2026-08-13 08:17:52'),
(178, 1, 109, '2026-09-07 21:12:52', '2026-09-27 21:12:52', 'PENDING', NULL, NULL),
(179, 1, 102, '2026-08-03 23:09:27', '2026-08-09 23:09:27', 'ACCEPTED', 67, '2026-07-30 23:09:27'),
(180, 1, 39, '2026-08-27 07:54:54', '2026-09-20 07:54:54', 'ACCEPTED', 65, '2026-08-23 07:54:54'),
(181, 1, 29, '2026-08-12 06:43:51', '2026-08-21 06:43:51', 'ACCEPTED', 63, '2026-08-08 06:43:51'),
(182, 1, 37, '2026-08-26 17:54:47', '2026-09-01 17:54:47', 'PENDING', NULL, NULL),
(183, 1, 9, '2026-08-23 21:29:55', '2026-09-10 21:29:55', 'ACCEPTED', 70, '2026-08-18 21:29:55'),
(184, 1, 129, '2026-08-15 22:11:35', '2026-09-12 22:11:35', 'ACCEPTED', 69, '2026-08-10 22:11:35'),
(185, 1, 44, '2026-08-30 23:51:18', '2026-09-17 23:51:18', 'PENDING', NULL, NULL),
(186, 1, 43, '2026-09-25 20:47:34', '2026-10-06 20:47:34', 'REJECTED', 53, '2026-09-23 20:47:34'),
(187, 1, 82, '2026-08-30 04:03:30', '2026-09-21 04:03:30', 'ACCEPTED', 57, '2026-08-25 04:03:30'),
(188, 1, 137, '2026-08-08 19:03:48', '2026-09-06 19:03:48', 'PENDING', NULL, NULL),
(189, 1, 17, '2026-09-18 14:13:12', '2026-10-05 14:13:12', 'PENDING', NULL, NULL),
(190, 1, 87, '2026-09-07 15:43:30', '2026-10-04 15:43:30', 'ACCEPTED', 55, '2026-09-03 15:43:30'),
(191, 1, 43, '2026-08-29 11:40:30', '2026-09-18 11:40:30', 'ACCEPTED', 66, '2026-08-27 11:40:30'),
(192, 1, 41, '2026-08-07 01:57:37', '2026-08-25 01:57:37', 'ACCEPTED', 66, '2026-08-04 01:57:37'),
(193, 1, 108, '2026-07-31 09:49:56', '2026-08-23 09:49:56', 'REJECTED', NULL, '2026-08-01 09:49:56'),
(194, 1, 41, '2026-09-07 06:06:30', '2026-09-22 06:06:30', 'PENDING', NULL, NULL),
(195, 1, 90, '2026-09-06 04:30:45', '2026-09-24 04:30:45', 'REJECTED', 67, '2026-09-03 04:30:45'),
(196, 1, 35, '2026-07-31 02:05:19', '2026-08-27 02:05:19', 'PENDING', NULL, NULL),
(197, 1, 45, '2026-08-11 07:26:02', '2026-08-18 07:26:02', 'PENDING', NULL, NULL),
(198, 1, 94, '2026-09-16 18:12:21', '2026-10-10 18:12:21', 'PENDING', NULL, NULL),
(199, 1, 27, '2026-08-21 18:07:46', '2026-08-26 18:07:46', 'PENDING', NULL, NULL),
(200, 1, 30, '2026-08-22 01:35:12', '2026-09-08 01:35:12', 'ACCEPTED', 64, '2026-08-19 01:35:12');

-- Storage Reservations
INSERT INTO storage_reservation (reservation_id, request_id, party_id, shelf_id, reserved_weight, reserved_volume, reserved_from, reserved_until, status) VALUES
(1, 2, 98, 2, 964.73, 7.82, '2026-08-17 07:19:51', '2026-09-07 07:19:51', 'ACTIVE'),
(8, 26, 133, 8, 580.01, 7.28, '2026-08-27 01:39:21', '2026-09-07 01:39:21', 'PENDING'),
(9, 27, 99, 10, 161.81, 1.34, '2026-09-04 09:30:01', '2026-09-23 09:30:01', 'CANCELLED'),
(12, 32, 47, 15, 522.47, 5.45, '2026-09-02 09:09:06', '2026-09-12 09:09:06', 'EXPIRED'),
(13, 34, 81, 14, 789.19, 2.08, '2026-08-18 13:17:46', '2026-09-14 13:17:46', 'ACTIVE'),
(14, 35, 4, 6, 259.71, 3.06, '2026-07-30 00:32:57', '2026-08-07 00:32:57', 'ACTIVE'),
(16, 37, 7, 5, 456.89, 1.67, '2026-09-16 11:10:32', '2026-10-11 11:10:32', 'PENDING'),
(18, 53, 40, 10, 755.01, 7.18, '2026-08-06 07:17:03', '2026-08-20 07:17:03', 'EXPIRED'),
(24, 70, 25, 8, 631.55, 4.61, '2026-08-30 22:24:17', '2026-09-14 22:24:17', 'ACTIVE'),
(25, 76, 90, 10, 840.3, 6.61, '2026-09-17 13:23:23', '2026-09-26 13:23:23', 'EXPIRED'),
(26, 77, 28, 2, 349.83, 1.77, '2026-09-06 16:50:37', '2026-09-13 16:50:37', 'CANCELLED'),
(29, 87, 74, 5, 647.6, 9.57, '2026-08-25 19:11:33', '2026-09-16 19:11:33', 'EXPIRED'),
(30, 91, 92, 2, 629.26, 1.82, '2026-08-06 04:58:56', '2026-08-11 04:58:56', 'EXPIRED'),
(31, 101, 19, 1, 441.41, 6.41, '2026-08-29 15:26:06', '2026-09-13 15:26:06', 'PENDING'),
(39, 116, 138, 5, 259.82, 7.93, '2026-09-11 03:22:11', '2026-09-22 03:22:11', 'EXPIRED'),
(40, 125, 11, 15, 590.48, 7.29, '2026-09-22 01:58:31', '2026-10-11 01:58:31', 'CANCELLED'),
(52, 156, 114, 6, 915.83, 4.79, '2026-08-14 20:31:50', '2026-09-04 20:31:50', 'PENDING'),
(54, 162, 48, 14, 584.61, 8.57, '2026-08-15 08:33:01', '2026-09-07 08:33:01', 'PENDING'),
(58, 179, 102, 12, 134.89, 2.56, '2026-08-03 23:09:27', '2026-08-09 23:09:27', 'PENDING'),
(67, 200, 30, 2, 475.26, 5.46, '2026-08-22 01:35:12', '2026-09-08 01:35:12', 'ACTIVE');

-- Storage Records
INSERT INTO storage_record (storage_record_id, request_id, party_id, shelf_id, actual_entry_date, actual_exit_date, cargo_description, cargo_weight, cargo_volume) VALUES
(1, 2, 98, 2, '2026-08-17 07:19:51', NULL, 'Would great peace.', 132.57, 7.81),
(2, 26, 133, 8, '2026-08-27 01:39:21', '2026-09-04 01:39:21', 'Water public than country in.', 757.58, 1.89),
(3, 27, 99, 10, '2026-09-04 09:30:01', NULL, 'Cost bill agency.', 966.31, 6.81),
(4, 32, 47, 15, '2026-09-02 09:09:06', '2026-09-03 09:09:06', 'Provide give reach administration.', 818.26, 6.82),
(5, 34, 81, 14, '2026-08-18 13:17:46', '2026-08-23 13:17:46', 'Small computer bring.', 656.99, 7.62),
(6, 35, 4, 6, '2026-07-30 00:32:57', '2026-07-31 00:32:57', 'Political agree yet idea.', 442.58, 3.43),
(7, 37, 7, 5, '2026-09-16 11:10:32', NULL, 'Today these sing.', 728.83, 9.63),
(8, 53, 40, 10, '2026-08-06 07:17:03', NULL, 'Every truth store must amount.', 769.99, 1.67),
(9, 70, 25, 8, '2026-08-30 22:24:17', NULL, 'Almost speak away.', 224.93, 2.38),
(10, 76, 90, 10, '2026-09-17 13:23:23', NULL, 'Positive level likely sit.', 671.54, 5.39),
(11, 77, 28, 2, '2026-09-06 16:50:37', NULL, 'New make.', 698.24, 9.0),
(12, 87, 74, 5, '2026-08-25 19:11:33', NULL, 'Member five attention.', 737.92, 1.32),
(13, 91, 92, 2, '2026-08-06 04:58:56', '2026-08-14 04:58:56', 'Anyone still size.', 807.81, 2.25),
(14, 101, 19, 1, '2026-08-29 15:26:06', NULL, 'Life as many.', 964.35, 6.15),
(15, 116, 138, 5, '2026-09-11 03:22:11', '2026-09-14 03:22:11', 'Republican point son spend.', 162.48, 3.74),
(16, 125, 11, 15, '2026-09-22 01:58:31', NULL, 'Series data age watch official.', 994.32, 2.98),
(17, 156, 114, 6, '2026-08-14 20:31:50', NULL, 'Family hope politics policy long.', 889.36, 8.66),
(18, 162, 48, 14, '2026-08-15 08:33:01', '2026-08-23 08:33:01', 'Few fund because experience.', 769.26, 3.35),
(19, 179, 102, 12, '2026-08-03 23:09:27', '2026-08-05 23:09:27', 'Join investment significant amount weight.', 500.76, 9.79),
(20, 200, 30, 2, '2026-08-22 01:35:12', '2026-08-26 01:35:12', 'Identify glass develop fund national.', 999.31, 1.98);

-- Cargo Event History
INSERT INTO cargo_event_history (event_id, party_id, storage_record_id, event_type_id, event_time, details) VALUES
(1, 66, 1, 1, '2026-08-05 23:15:46', '{"note": "Lot plant set cultural.", "performed_by": "Craig Moore", "location": "better"}'::jsonb),
(2, 64, 2, 2, '2026-08-17 21:56:35', '{"note": "Big behavior trip eye produce few.", "performed_by": "Nicholas Rowland", "location": "fact"}'::jsonb),
(3, 53, 3, 3, '2026-08-26 20:22:29', '{"note": "Every analysis someone.", "performed_by": "Larry Thompson", "location": "dog"}'::jsonb),
(4, 62, 4, 4, '2026-08-09 05:49:18', '{"note": "Throw relate song drop doctor brother help.", "performed_by": "Karen Hughes", "location": "where"}'::jsonb);

-- Payments
INSERT INTO payment (payment_id, storage_record_id, party_id, amount, currency, status, payment_date, external_reference) VALUES
(1, 1, 134, 1791.88, 'USD', 'PENDING', NULL, 'PAY-20260827-0001'),
(2, 2, 24, 966.37, 'EUR', 'PAID', '2026-08-08 13:09:38', 'PAY-20260827-0002'),
(3, 3, 135, 604.51, 'PLN', 'PENDING', NULL, 'PAY-20260827-0003'),
(4, 4, 83, 1892.93, 'PLN', 'PENDING', NULL, 'PAY-20260827-0004'),
(5, 5, 48, 1163.87, 'USD', 'CANCELLED', '2026-08-23 10:36:03', 'PAY-20260827-0005'),
(6, 6, 134, 923.4, 'EUR', 'FAILED', '2026-08-19 13:08:18', 'PAY-20260827-0006'),
(7, 7, 23, 829.96, 'PLN', 'PAID', '2026-08-24 17:42:47', 'PAY-20260827-0007'),
(8, 8, 18, 1163.98, 'USD', 'PAID', '2026-08-17 08:57:01', 'PAY-20260827-0008'),
(9, 9, 75, 1802.72, 'USD', 'PENDING', NULL, 'PAY-20260827-0009'),
(10, 10, 109, 848.94, 'EUR', 'FAILED', '2026-07-30 15:38:47', 'PAY-20260827-0010'),
(11, 11, 35, 665.89, 'USD', 'FAILED', '2026-08-18 09:56:55', 'PAY-20260827-0011'),
(12, 12, 83, 562.44, 'EUR', 'PAID', '2026-08-22 16:20:55', 'PAY-20260827-0012'),
(13, 13, 77, 919.46, 'USD', 'PAID', '2026-08-21 16:22:16', 'PAY-20260827-0013'),
(14, 14, 39, 1759.69, 'PLN', 'PAID', '2026-08-02 20:33:04', 'PAY-20260827-0014'),
(15, 15, 43, 527.52, 'USD', 'PENDING', NULL, 'PAY-20260827-0015'),
(16, 16, 10, 1533.73, 'EUR', 'PENDING', NULL, 'PAY-20260827-0016'),
(17, 17, 15, 1374.51, 'USD', 'PAID', '2026-08-04 12:21:05', 'PAY-20260827-0017'),
(18, 18, 13, 637.82, 'PLN', 'FAILED', '2026-08-19 19:18:23', 'PAY-20260827-0018'),
(19, 19, 32, 1633.98, 'PLN', 'FAILED', '2026-08-19 09:07:28', 'PAY-20260827-0019'),
(20, 20, 18, 752.71, 'PLN', 'CANCELLED', '2026-08-12 16:51:15', 'PAY-20260827-0020'),
(21, 1, 31, 787.11, 'PLN', 'CANCELLED', '2026-08-17 05:36:52', 'PAY-20260827-0021'),
(22, 2, 84, 1408.72, 'EUR', 'FAILED', '2026-08-27 09:36:06', 'PAY-20260827-0022'),
(23, 3, 87, 595.7, 'USD', 'CANCELLED', '2026-08-20 08:14:40', 'PAY-20260827-0023'),
(24, 4, 1, 923.94, 'EUR', 'PENDING', NULL, 'PAY-20260827-0024'),
(25, 5, 9, 1937.43, 'EUR', 'FAILED', '2026-08-23 00:01:44', 'PAY-20260827-0025'),
(26, 6, 90, 645.55, 'USD', 'FAILED', '2026-08-12 04:10:36', 'PAY-20260827-0026'),
(27, 7, 88, 1132.08, 'PLN', 'FAILED', '2026-08-01 00:40:08', 'PAY-20260827-0027'),
(28, 8, 44, 1567.19, 'EUR', 'FAILED', '2026-08-10 13:06:35', 'PAY-20260827-0028'),
(29, 9, 2, 649.45, 'PLN', 'CANCELLED', '2026-08-12 19:19:27', 'PAY-20260827-0029'),
(30, 10, 71, 1301.34, 'PLN', 'PAID', '2026-08-06 16:10:40', 'PAY-20260827-0030'),
(31, 11, 84, 1814.73, 'EUR', 'PAID', '2026-07-29 12:44:10', 'PAY-20260827-0031'),
(32, 12, 91, 753.0, 'USD', 'PAID', '2026-08-23 14:22:05', 'PAY-20260827-0032'),
(33, 13, 44, 888.87, 'PLN', 'PAID', '2026-08-02 16:59:42', 'PAY-20260827-0033'),
(34, 14, 84, 1300.13, 'USD', 'CANCELLED', '2026-07-31 19:22:59', 'PAY-20260827-0034'),
(35, 15, 90, 1214.73, 'PLN', 'CANCELLED', '2026-08-08 14:08:06', 'PAY-20260827-0035'),
(36, 16, 94, 953.0, 'USD', 'PAID', '2026-08-10 01:00:57', 'PAY-20260827-0036'),
(37, 17, 77, 669.68, 'PLN', 'PENDING', NULL, 'PAY-20260827-0037'),
(38, 18, 133, 1280.06, 'EUR', 'PAID', '2026-07-30 21:47:24', 'PAY-20260827-0038'),
(39, 19, 128, 1510.33, 'EUR', 'CANCELLED', '2026-08-02 17:41:20', 'PAY-20260827-0039'),
(40, 20, 113, 864.59, 'PLN', 'CANCELLED', '2026-08-05 00:51:53', 'PAY-20260827-0040');

-- Align SERIAL sequences with the explicitly inserted ids
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT seq.relname AS sequence_name,
               tbl.relname AS table_name,
               att.attname AS column_name
        FROM pg_class seq
        JOIN pg_depend dep ON dep.objid = seq.oid AND seq.relkind = 'S'
        JOIN pg_class tbl ON tbl.oid = dep.refobjid
        JOIN pg_attribute att ON att.attrelid = tbl.oid AND att.attnum = dep.refobjsubid
        JOIN pg_namespace nsp ON nsp.oid = seq.relnamespace AND nsp.nspname = 'public'
    LOOP
        EXECUTE format(
            'SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, false)',
            rec.sequence_name, rec.column_name, rec.table_name
        );
    END LOOP;
END $$;
