import { Document } from '@/model/documents'
import { PdfDocumentSpec } from '@/lib/pdf/pdf.model'
import { formatDateTime, sanitizeFilenamePart } from '@/lib/pdf/pdf.format'

export interface DocumentPdfOptions {
  includeWatermark?: boolean
}

const DOCUMENT_TYPE_LABELS: Record<Document['type'], string> = {
  'contract': 'Contract',
  'invoice': 'Invoice',
  'registration': 'Vehicle Registration',
  'insurance': 'Insurance Policy',
  'inspection': 'Technical Inspection Certificate',
  'tir-carnet': 'TIR Carnet',
  'adr': 'ADR Certificate',
  'hazmat-permit': 'Hazmat Transport Permit',
  'license': 'License',
  'certificate': 'Certificate',
  'other': 'Document',
}

const ENTITY_TYPE_LABELS: Record<Document['entityType'], string> = {
  'vehicle': 'Vehicle',
  'customer': 'Customer',
  'supplier': 'Supplier',
  'driver': 'Driver',
  'company': 'Company',
  'other': 'Other',
}

function getDocumentTypeLabel(type: Document['type']): string {
  return DOCUMENT_TYPE_LABELS[type]
}

function getEntityTypeLabel(type: Document['entityType']): string {
  return ENTITY_TYPE_LABELS[type]
}

export function documentToPdfSpec(document: Document, options: DocumentPdfOptions = {}): PdfDocumentSpec {
  const blocks: PdfDocumentSpec['blocks'] = [
    {
      kind: 'section',
      title: 'Document Information',
      blocks: [
        { kind: 'field', label: 'Document Name:', value: document.name },
        { kind: 'field', label: 'Document Type:', value: getDocumentTypeLabel(document.type) },
        { kind: 'field', label: 'Document ID:', value: document.id },
        { kind: 'field', label: 'Document Number:', value: document.number },
      ],
    },
    {
      kind: 'section',
      title: 'Related Entity',
      blocks: [
        { kind: 'field', label: 'Related To:', value: getEntityTypeLabel(document.entityType) },
        { kind: 'field', label: 'Entity Name:', value: document.entityName },
        { kind: 'field', label: 'Entity ID:', value: document.entityId },
      ],
    },
    {
      kind: 'section',
      title: 'Important Dates',
      blocks: [
        { kind: 'field', label: 'Issue Date:', value: formatDateTime(document.issueDate) },
        {
          kind: 'field',
          label: 'Expiry Date:',
          value: document.expiryDate ? formatDateTime(document.expiryDate) : undefined,
        },
        { kind: 'field', label: 'Created:', value: formatDateTime(document.createdAt) },
        { kind: 'field', label: 'Last Updated:', value: formatDateTime(document.updatedAt) },
      ],
    },
  ]

  if (document.issuingAuthority) {
    blocks.push({
      kind: 'section',
      title: 'Issuing Authority',
      blocks: [{ kind: 'field', label: 'Authority:', value: document.issuingAuthority }],
    })
  }

  if (document.notes) {
    blocks.push({
      kind: 'section',
      title: 'Notes',
      blocks: [{ kind: 'paragraph', text: document.notes }],
    })
  }

  blocks.push({
    kind: 'section',
    title: 'Document Content',
    blocks: [
      { kind: 'paragraph', text: 'This is a sample document generated by the Deliveroo TMS system.' },
      { kind: 'paragraph', text: 'This document contains all the relevant information as stored in the system.' },
    ],
  })

  return {
    title: getDocumentTypeLabel(document.type),
    filename: `${sanitizeFilenamePart(document.name).toLowerCase()}_${document.id}.pdf`,
    watermark: options.includeWatermark ? 'SAMPLE DOCUMENT' : undefined,
    blocks,
  }
}
