# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class LooseBoolean(RootModel[Literal['true', 'false', '1', '0', 'yes', 'no']]):
    root: Literal['true', 'false', '1', '0', 'yes', 'no']
    """
    A boolean query flag. Accepted spellings are `true`/`1`/`yes` and
    `false`/`0`/`no`; anything else is a `400 invalid_query`.

    """


class LegacyError(BaseModel):
    """
    The legacy error shape - a single `error` key holding human-readable
    text, not a machine-readable code.

    `message` appears when the failure came from the router rather than the
    handler - a URL that matched no rule at all answers with the same
    envelope as the rest of the API.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    error: Annotated[str, Field(examples=['Employee id 999 not found'])]
    message: str | None = None
    """
    Present only on router-level failures.
    """


class Detail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Annotated[str, Field(examples=['width.value'])]
    message: Annotated[str, Field(examples=['Input should be greater than 0'])]


class ApiError(BaseModel):
    """
    The topology error envelope: a machine-readable `code` in `error`, human
    text in `message`, plus whatever context the specific failure carries
    (`details`, `constraint`, `hint`, ...).

    """

    model_config = ConfigDict(
        extra='allow',
    )
    error: Annotated[str, Field(examples=['invalid_body'])]
    """
    Machine-readable error code.
    """
    message: Annotated[str, Field(examples=['Request body failed validation.'])]
    """
    Human-readable explanation.
    """
    details: list[Detail] | None = None
    """
    Present on validation failures - one entry per offending field.
    """
    constraint: str | None = None
    """
    Present on database conflicts - the index that collided.
    """
    hint: str | None = None
    """
    Present when there is a concrete next step, e.g. retry with `?cascade=true`.
    """


class BulkNotFoundError(BaseModel):
    """
    `PATCH /shelves:bulk` with at least one unknown id.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    error: Literal['not_found']
    message: str
    missing: Annotated[list[int], Field(max_length=100)]
    """
    Up to 100 of the ids that do not exist.
    """


class BlockedShelf(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shelf_id: int
    code: Annotated[str, Field(examples=['BULK-A01-R001-L1'])]
    reason: Literal['in_use', 'has_history']
    """
    `in_use` - a pending/active reservation or an open storage record.
    `has_history` - only closed records remain, but the trace blocks the
    delete all the same.

    """
    reservations: Annotated[int, Field(ge=0)]
    records: Annotated[int, Field(ge=0)]


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['UP', 'DOWN']
    """
    `DOWN` as soon as any dependency is down.
    """
    timestamp: float
    """
    Unix epoch seconds at the moment of the check.
    """
    uptime_seconds: Annotated[int, Field(ge=0)]
    version: str | None = None
    """
    From the `VERSION` environment variable, `1.0.0` if unset.
    """
    dependencies: dict[str, Literal['UP', 'DOWN']]
    """
    One entry per checked dependency.
    """


class StorageEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: int
    storage_record_id: int
    event_type_id: int
    event_time: Annotated[
        str,
        Field(
            examples=['Wed, 11 Dec 2024 06:50:57 GMT'],
            pattern='^[A-Z][a-z]{2}, \\d{2} [A-Z][a-z]{2} \\d{4} \\d{2}:\\d{2}:\\d{2} GMT$',
        ),
    ]
    """
    A timestamp rendered by Flask's default JSON encoder (RFC 1123 / RFC 7231
    HTTP-date), e.g. `Wed, 11 Dec 2024 06:50:57 GMT`. Deliberately *not*
    `format: date-time` - that would assert RFC 3339, which this is not.

    """
    party_id: Annotated[int | None, Field(...)]
    details: Annotated[dict[str, Any] | None, Field(...)]
    """
    Free-form JSONB payload; the keys vary by event type.
    """


class EmployeeListItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    employee_id: int
    employee_name: str
    email: Annotated[str | None, Field(...)]
    phone: Annotated[str | None, Field(...)]
    hire_date: Annotated[
        str | None,
        Field(
            pattern='^[A-Z][a-z]{2}, \\d{2} [A-Z][a-z]{2} \\d{4} \\d{2}:\\d{2}:\\d{2} GMT$'
        ),
    ]
    """
    See `HttpDate` - RFC 1123, not RFC 3339.
    """
    roles: Annotated[str | None, Field(examples=['OPERATOR, SUPERVISOR'])]
    """
    Role names joined with `, `.
    """


class Contact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[str | None, Field(examples=['EMAIL'])]
    details: Annotated[str | None, Field(examples=['info@example.com'])]


class ContractorSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(examples=['1'])]
    """
    `party_id`, serialised as a string by the contract layer.
    """
    name: str
    status: Literal['ACTIVE', 'INACTIVE']
    tax_id_number: Annotated[str | None, Field(...)]
    contacts: list[Contact]


class AddressDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address_id: Annotated[str | None, Field(...)]
    street_address: Annotated[str | None, Field(...)]
    city: Annotated[str | None, Field(...)]
    country: Annotated[str | None, Field(...)]
    postal_code: Annotated[str | None, Field(...)]
    address_type: Annotated[str | None, Field(...)]


class EmployeeSummaryEmployeeData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str | None = None
    job_title: str | None = None


class EmployeeSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    employee_id: Annotated[str | None, Field(...)]
    employee_name: Annotated[str | None, Field(...)]
    employee_data: EmployeeSummaryEmployeeData
    contacts: Annotated[list[Contact] | None, Field(...)]


class ContractorDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(examples=['1'])]
    name: str
    status: Literal['ACTIVE', 'INACTIVE']
    tax_id_number: Annotated[str | None, Field(...)]
    created_at: Annotated[
        str | None,
        Field(
            pattern='^[A-Z][a-z]{2}, \\d{2} [A-Z][a-z]{2} \\d{4} \\d{2}:\\d{2}:\\d{2} GMT$'
        ),
    ]
    """
    See `HttpDate` - RFC 1123, not RFC 3339.
    """
    updated_at: Annotated[
        str | None,
        Field(
            pattern='^[A-Z][a-z]{2}, \\d{2} [A-Z][a-z]{2} \\d{4} \\d{2}:\\d{2}:\\d{2} GMT$'
        ),
    ]
    """
    See `HttpDate` - RFC 1123, not RFC 3339.
    """
    contacts: list[Contact]
    addresses: list[AddressDetails]
    employees: list[EmployeeSummary]


class ContractorStatusUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ACTIVE', 'INACTIVE']


class ContractorStatusUpdateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Annotated[
        str, Field(examples=['Contractor 1 status updated successfully to ACTIVE'])
    ]


class Payment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payment_id: int
    storage_record_id: Annotated[int | None, Field(...)]
    party_id: Annotated[int | None, Field(...)]
    amount: Annotated[
        str | None, Field(examples=['1814.73'], pattern='^-?\\d+(\\.\\d+)?$')
    ]
    """
    A Postgres `NUMERIC` column, serialised by Flask as a **string** so no
    precision is lost on the wire. Clients must not assume a JSON number.

    """
    currency: Annotated[str | None, Field(examples=['EUR'])]
    status: Annotated[str | None, Field(examples=['PAID'])]
    payment_date: Annotated[
        str | None,
        Field(
            pattern='^[A-Z][a-z]{2}, \\d{2} [A-Z][a-z]{2} \\d{4} \\d{2}:\\d{2}:\\d{2} GMT$'
        ),
    ]
    """
    See `HttpDate` - RFC 1123, not RFC 3339.
    """
    external_reference: Annotated[str | None, Field(examples=['PAY-20260827-0031'])]


class LengthInput1(RootModel[int]):
    root: Annotated[
        int, Field(examples=[{'value': 500, 'unit': 'cm'}], gt=0, le=2147483647)
    ]
    """
    Millimetres.
    """


class LengthInput2(BaseModel):
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[int, Field(gt=0, le=2147483647)]
    unit: Literal['mm', 'cm', 'm'] = 'mm'


class WeightInput1(RootModel[float]):
    root: Annotated[
        float, Field(examples=[{'value': 700, 'unit': 'kg'}], gt=0.0, le=1000000000.0)
    ]
    """
    Kilograms.
    """


class WeightInput2(BaseModel):
    """
    A weight. A bare number means kilograms. Explicit units are **normalised
    to kg on write** and always read back as kg.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[float, Field(gt=0.0, le=1000000000.0)]
    unit: Literal['g', 'kg', 't'] = 'kg'


class VolumeInput1(RootModel[float]):
    root: Annotated[
        float, Field(examples=[{'value': 6, 'unit': 'm3'}], gt=0.0, le=1000000000.0)
    ]
    """
    Cubic metres.
    """


class VolumeInput2(BaseModel):
    """
    A volume. A bare number means cubic metres. Explicit units are
    **normalised to m3 on write** and always read back as m3.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[float, Field(gt=0.0, le=1000000000.0)]
    unit: Literal['cm3', 'l', 'm3'] = 'm3'


class LengthOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float
    unit: Literal['mm', 'cm', 'm']


class WeightOutput(BaseModel):
    """
    Always kilograms - weights are normalised on write.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: float
    unit: Literal['kg']


class VolumeOutput(BaseModel):
    """
    Always cubic metres - volumes are normalised on write.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: float
    unit: Literal['m3']


class LabelSpec1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['01..08'],
            max_length=34,
            min_length=1,
            pattern='^([A-Za-z0-9_]{1,16}|[A-Za-z_]*[0-9]+\\.\\.[A-Za-z_]*[0-9]+)$',
        ),
    ]
    """
    Either a range (`"01..08"`, zero-padding taken from the left operand, a
    matching non-numeric prefix required on both sides), a single label, or
    an explicit list. Labels are `[A-Za-z0-9_]` because `-` separates the
    segments of the composed shelf path.

    The two forms are spelled out rather than described, so a label the
    expander would refuse is a `400` from the contract instead of a `400`
    from a hundred lines further in.

    """


class LabelSpec2Item(RootModel[str]):
    root: Annotated[str, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')]


class LabelSpec2(RootModel[list[LabelSpec2Item]]):
    root: Annotated[
        list[LabelSpec2Item], Field(examples=[['A01', 'A02']], min_length=1)
    ]
    """
    Either a range (`"01..08"`, zero-padding taken from the left operand, a
    matching non-numeric prefix required on both sides), a single label, or
    an explicit list. Labels are `[A-Za-z0-9_]` because `-` separates the
    segments of the composed shelf path.

    The two forms are spelled out rather than described, so a label the
    expander would refuse is a `400` from the contract instead of a `400`
    from a hundred lines further in.

    """


class LevelSpec1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['1..4'],
            max_length=18,
            min_length=1,
            pattern='^([A-Za-z0-9_]{1,8}|[A-Za-z_]*[0-9]+\\.\\.[A-Za-z_]*[0-9]+)$',
        ),
    ]
    """
    Same grammar as `LabelSpec`, but levels are capped at 8 characters.
    """


class LevelSpec2Item(RootModel[str]):
    root: Annotated[str, Field(max_length=8, min_length=1, pattern='^[A-Za-z0-9_]+$')]


class LevelSpec2(RootModel[list[LevelSpec2Item]]):
    root: Annotated[
        list[LevelSpec2Item], Field(examples=[['1', '2', '3']], min_length=1)
    ]
    """
    Same grammar as `LabelSpec`, but levels are capped at 8 characters.
    """


class Location(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    address: str
    city: str
    postal_code: str
    country: str


class Warehouse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    name: str
    description: Annotated[str | None, Field(...)]
    location: Location
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """


class Zone(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    warehouse_id: int
    code: Annotated[str, Field(examples=['BULK'])]
    """
    First segment of the composed shelf path, unique per warehouse.
    """
    name: str
    description: Annotated[str | None, Field(...)]
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """


class Aisle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    zone_id: int
    label: Annotated[str, Field(examples=['A01'])]
    width: LengthOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """


class Rack(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    aisle_id: int
    label: Annotated[str, Field(examples=['R001'])]
    max_height: LengthOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """


class Shelf(BaseModel):
    """
    A shelf addressed within its rack. See `ShelfWithPath` for the catalogue shape.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    rack_id: int
    level: Annotated[str, Field(examples=['1'])]
    code: Annotated[str | None, Field(examples=['BULK-A01-R001-L1'])]
    """
    The composed path `{zone}-{aisle}-{rack}-L{level}`. Never stored - it
    is composed on read and is unique by construction.

    """
    max_weight: WeightOutput
    max_volume: VolumeOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """


class Zone1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    code: str


class Aisle1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    label: str


class Rack1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    label: str


class ShelfWithPath(BaseModel):
    """
    The `GET /shelves` shape - a shelf plus the chain up to its warehouse, so
    the catalogue is readable without a second call.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    rack_id: int
    level: str
    code: Annotated[str | None, Field(examples=['BULK-A01-R001-L1'])]
    max_weight: WeightOutput
    max_volume: VolumeOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    warehouse_id: int
    zone: Zone1
    aisle: Aisle1
    rack: Rack1


class LocationPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Location]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class WarehousePage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Warehouse]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class ZonePage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Zone]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class AislePage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Aisle]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class RackPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Rack]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class ShelfPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Shelf]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class ShelfWithPathPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ShelfWithPath]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1)]
    total: Annotated[int, Field(ge=0)]


class LocationCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: Annotated[
        str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')
    ]
    city: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')]
    postal_code: Annotated[
        str, Field(max_length=20, min_length=1, pattern='^[^\\u0000]*$')
    ]
    country: Annotated[
        str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')
    ]


class WarehouseCreate1(BaseModel):
    """
    Exactly one of `location_id` (an existing address) or `location` (a new
    one, created in the same transaction) is required.

    The `oneOf` below is that rule, not a restatement of it: send both or
    neither and the contract rejects the call before the handler does.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')]
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None
    location_id: Annotated[int, Field(gt=0)]
    """
    An existing location. Mutually exclusive with `location`.
    """
    location: LocationCreate | None = None
    """
    A new location, created in the same transaction. Mutually exclusive with `location_id`.
    """


class WarehouseCreate2(BaseModel):
    """
    Exactly one of `location_id` (an existing address) or `location` (a new
    one, created in the same transaction) is required.

    The `oneOf` below is that rule, not a restatement of it: send both or
    neither and the contract rejects the call before the handler does.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')]
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None
    location_id: Annotated[int | None, Field(gt=0)] = None
    """
    An existing location. Mutually exclusive with `location`.
    """
    location: LocationCreate
    """
    A new location, created in the same transaction. Mutually exclusive with `location_id`.
    """


class WarehouseCreate(RootModel[WarehouseCreate1 | WarehouseCreate2]):
    root: WarehouseCreate1 | WarehouseCreate2
    """
    Exactly one of `location_id` (an existing address) or `location` (a new
    one, created in the same transaction) is required.

    The `oneOf` below is that rule, not a restatement of it: send both or
    neither and the contract rejects the call before the handler does.

    """


class WarehousePatch(BaseModel):
    """
    At least one field must be present.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        str | None, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')
    ] = None
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None
    location_id: Annotated[int | None, Field(gt=0)] = None


class ZoneCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')]
    name: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')]
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None


class ZonePatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[
        str | None, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')
    ] = None
    name: Annotated[
        str | None, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')
    ] = None
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None


class AisleCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: Annotated[str, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')]
    width: Annotated[
        LengthInput1 | LengthInput2, Field(examples=[{'value': 500, 'unit': 'cm'}])
    ]
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """


class AislePatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: Annotated[
        str | None, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')
    ] = None
    width: Annotated[
        LengthInput1 | LengthInput2 | None,
        Field(examples=[{'value': 500, 'unit': 'cm'}]),
    ] = None
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """


class RackCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: Annotated[str, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')]
    max_height: Annotated[
        LengthInput1 | LengthInput2, Field(examples=[{'value': 500, 'unit': 'cm'}])
    ]
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """


class RackPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: Annotated[
        str | None, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')
    ] = None
    max_height: Annotated[
        LengthInput1 | LengthInput2 | None,
        Field(examples=[{'value': 500, 'unit': 'cm'}]),
    ] = None
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """


class ShelfCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Annotated[str, Field(max_length=8, min_length=1, pattern='^[A-Za-z0-9_]+$')]
    max_weight: Annotated[
        WeightInput1 | WeightInput2, Field(examples=[{'value': 700, 'unit': 'kg'}])
    ]
    """
    A weight. A bare number means kilograms. Explicit units are **normalised
    to kg on write** and always read back as kg.

    """
    max_volume: Annotated[
        VolumeInput1 | VolumeInput2, Field(examples=[{'value': 6, 'unit': 'm3'}])
    ]
    """
    A volume. A bare number means cubic metres. Explicit units are
    **normalised to m3 on write** and always read back as m3.

    """


class ShelfPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Annotated[
        str | None, Field(max_length=8, min_length=1, pattern='^[A-Za-z0-9_]+$')
    ] = None
    max_weight: Annotated[
        WeightInput1 | WeightInput2 | None,
        Field(examples=[{'value': 700, 'unit': 'kg'}]),
    ] = None
    """
    A weight. A bare number means kilograms. Explicit units are **normalised
    to kg on write** and always read back as kg.

    """
    max_volume: Annotated[
        VolumeInput1 | VolumeInput2 | None, Field(examples=[{'value': 6, 'unit': 'm3'}])
    ] = None
    """
    A volume. A bare number means cubic metres. Explicit units are
    **normalised to m3 on write** and always read back as m3.

    """


class ShelfBulkPatchBody(BaseModel):
    """
    `level` is deliberately absent - it is unique per rack.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    max_weight: Annotated[
        WeightInput1 | WeightInput2 | None,
        Field(examples=[{'value': 700, 'unit': 'kg'}]),
    ] = None
    """
    A weight. A bare number means kilograms. Explicit units are **normalised
    to kg on write** and always read back as kg.

    """
    max_volume: Annotated[
        VolumeInput1 | VolumeInput2 | None, Field(examples=[{'value': 6, 'unit': 'm3'}])
    ] = None
    """
    A volume. A bare number means cubic metres. Explicit units are
    **normalised to m3 on write** and always read back as m3.

    """


class ShelfBulkPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: Annotated[list[int], Field(max_length=5000, min_length=1)]
    patch: ShelfBulkPatchBody


class ShelfBulkPatchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updated: Annotated[int, Field(ge=0)]
    items: list[Shelf]


class ShelfTemplate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    per_rack: Annotated[int | None, Field(gt=0)] = None
    """
    Optional redundant count of the shelves per rack. If given it must
    equal the number of levels `levels` expands to; a mismatch is a
    `400 inconsistent_request`. JSON Schema cannot state "this integer
    equals the length of that list after a range is expanded", so this
    is one rule the server checks and the contract can only describe.

    """
    levels: LevelSpec1 | LevelSpec2
    """
    Same grammar as `LabelSpec`, but levels are capped at 8 characters.
    """
    max_weight: Annotated[
        WeightInput1 | WeightInput2, Field(examples=[{'value': 700, 'unit': 'kg'}])
    ]
    """
    A weight. A bare number means kilograms. Explicit units are **normalised
    to kg on write** and always read back as kg.

    """
    max_volume: Annotated[
        VolumeInput1 | VolumeInput2, Field(examples=[{'value': 6, 'unit': 'm3'}])
    ]
    """
    A volume. A bare number means cubic metres. Explicit units are
    **normalised to m3 on write** and always read back as m3.

    """


class RackTemplate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    per_aisle: Annotated[int | None, Field(gt=0)] = None
    """
    Optional redundant count of the racks per aisle. If given it must
    equal what `labels` expands to; a mismatch is a
    `400 inconsistent_request`. See `ShelfTemplate.per_rack`.

    """
    labels: LabelSpec1 | LabelSpec2
    """
    Either a range (`"01..08"`, zero-padding taken from the left operand, a
    matching non-numeric prefix required on both sides), a single label, or
    an explicit list. Labels are `[A-Za-z0-9_]` because `-` separates the
    segments of the composed shelf path.

    The two forms are spelled out rather than described, so a label the
    expander would refuse is a `400` from the contract instead of a `400`
    from a hundred lines further in.

    """
    max_height: Annotated[
        LengthInput1 | LengthInput2, Field(examples=[{'value': 500, 'unit': 'cm'}])
    ]
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """
    shelves: ShelfTemplate | None = None


class AisleTemplate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: Annotated[int | None, Field(gt=0)] = None
    """
    Optional redundant count of the aisles. If given it must equal what
    `labels` expands to; a mismatch is a `400 inconsistent_request`.
    See `ShelfTemplate.per_rack`.

    """
    labels: LabelSpec1 | LabelSpec2
    """
    Either a range (`"01..08"`, zero-padding taken from the left operand, a
    matching non-numeric prefix required on both sides), a single label, or
    an explicit list. Labels are `[A-Za-z0-9_]` because `-` separates the
    segments of the composed shelf path.

    The two forms are spelled out rather than described, so a label the
    expander would refuse is a `400` from the contract instead of a `400`
    from a hundred lines further in.

    """
    width: Annotated[
        LengthInput1 | LengthInput2, Field(examples=[{'value': 500, 'unit': 'cm'}])
    ]
    """
    A length. Either a bare integer - meaning millimetres, the base unit - or
    an explicit `{value, unit}`. Lengths are stored **verbatim** together
    with the unit the caller sent.

    The ceiling is the width of the `INTEGER` column the value lands in.
    Without it an oversized length reaches Postgres and fails there, which
    would be a 500 for what is plainly a bad request.

    """
    racks: RackTemplate | None = None


class AisleGenerate(AisleTemplate):
    """
    Body of `POST /zones/{zone_id}/aisles:generate`.
    """


class RackGenerate(RackTemplate):
    """
    Body of `POST /aisles/{aisle_id}/racks:generate`.
    """


class ShelfGenerate(ShelfTemplate):
    """
    Body of `POST /racks/{rack_id}/shelves:generate`.
    """


class LayoutZoneSpec(BaseModel):
    """
    A zone plus what to build underneath it. `racks` needs `aisles` and
    `shelves` needs `racks` - there would be nothing to hang them off.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=16, min_length=1, pattern='^[A-Za-z0-9_]+$')]
    name: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^\\u0000]*$')]
    description: Annotated[
        str | None, Field(max_length=2000, pattern='^[^\\u0000]*$')
    ] = None
    aisles: AisleTemplate | None = None
    racks: RackTemplate | None = None
    shelves: ShelfTemplate | None = None


class LayoutCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    naming: Literal['{zone}-{aisle}-{rack}-L{level}'] | None = None
    """
    Accepted only with the one canonical value. The composed path is
    never stored, so a per-request template would have nothing to write
    to.

    """
    zones: Annotated[list[LayoutZoneSpec], Field(max_length=50, min_length=1)]


class TopologyCounts(BaseModel):
    """
    Row counts per level. Which keys are present depends on the level the
    call addressed - a zone delete reports `zones`, an aisle delete does not.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    zones: Annotated[int | None, Field(ge=0)] = None
    aisles: Annotated[int | None, Field(ge=0)] = None
    racks: Annotated[int | None, Field(ge=0)] = None
    shelves: Annotated[int | None, Field(ge=0)] = None


class LayoutRackNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    aisle_id: int
    label: str
    max_height: LengthOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    counts: TopologyCounts
    shelves: list[Shelf] | None = None
    """
    Present only at `depth=shelf`.
    """


class LayoutAisleNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    zone_id: int
    label: str
    width: LengthOutput
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    counts: TopologyCounts
    racks: list[LayoutRackNode] | None = None
    """
    Present from `depth=rack` downwards.
    """


class LayoutZoneNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    warehouse_id: int
    code: str
    name: str
    description: Annotated[str | None, Field(...)]
    created_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    updated_at: Annotated[
        str,
        Field(
            examples=['2026-08-27T12:13:55.537725'],
            pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?$',
        ),
    ]
    """
    `datetime.isoformat()` of a Postgres `TIMESTAMP` column - ISO-8601 with
    no UTC offset, e.g. `2026-08-27T12:13:55.537725`. Values are UTC by
    convention. Deliberately *not* `format: date-time`, which would assert an
    offset that is not there.

    """
    counts: TopologyCounts
    aisles: list[LayoutAisleNode] | None = None
    """
    Present from `depth=aisle` downwards.
    """


class Layout(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warehouse: Warehouse
    depth: Literal['zone', 'aisle', 'rack', 'shelf']
    counts: TopologyCounts
    zones: list[LayoutZoneNode]


class LayoutCreated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created: TopologyCounts
    naming: Annotated[str, Field(examples=['{zone}-{aisle}-{rack}-L{level}'])]
    zones: list[Zone]


class LayoutDryRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    would_create: TopologyCounts
    naming: Annotated[str, Field(examples=['{zone}-{aisle}-{rack}-L{level}'])]


class DeleteDryRun(BaseModel):
    """
    What a real `DELETE` would have removed. Nothing was written.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    would_delete: TopologyCounts


class GenerateDryRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    would_create: TopologyCounts


class AislesGenerated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created: TopologyCounts
    aisles: list[Aisle]


class RacksGenerated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created: TopologyCounts
    racks: list[Rack]


class ShelvesGenerated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created: TopologyCounts
    shelves: list[Shelf]


class LegacyOrGuardError(RootModel[LegacyError | ApiError]):
    root: LegacyError | ApiError
    """
    A failure on a legacy endpoint comes from one of two places, and they do
    not share a shape: the handler answers with `LegacyError`, while the
    contract guard - which runs before the handler and rejects bad
    parameters, headers and bodies - answers with the `ApiError` envelope
    used everywhere else.

    """


class DeleteBlockedError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    error: Literal['in_use', 'has_history', 'has_children']
    message: str
    blocked_count: Annotated[int | None, Field(ge=0)] = None
    """
    How many shelves block the delete (`in_use` / `has_history`).
    """
    blocked_by: Annotated[list[BlockedShelf] | None, Field(max_length=20)] = None
    """
    Up to 20 of the blocking shelves; `blocked_count` tells the whole truth.
    """
    would_delete: TopologyCounts | None = None
    child_counts: TopologyCounts | None = None
    hint: str | None = None
