{
 "title": "(OTLP) Metrics Dashboard",
 "templating": {
  "list": [
   {
    "name": "route",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health (NO PARAMS HERE)",
   "type": "timeseries",
   "description": "1 - UP\n0 - DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "health_status_ratio", "legendFormat": "HEALTHY" }
   ]
  },
  {
   "title": "Request Rate (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "description": "Calculates the average request rate(requests per second, RPS) for a specific set of HTTP routes and methods over a rolling window that adapts to the dashboard resolution (`$__rate_interval`).\n\nIt uses the `sum(rate(...))` combination to aggregate the increase in the `http_server_duration_milliseconds_count` counter, dividing the result into distinct time series based on the `http_route` and `http_method` labels. This provides a clear breakdown of the load each unique route and method combination is currently experiencing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "# http_server_duration_milliseconds_count\n# http_server_duration_milliseconds_count{http_route=~\"$route\", http_method=~\"$method\"}\n# rate(http_server_duration_milliseconds_count{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])\n\nsum(rate(http_server_duration_milliseconds_count{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (http_route, http_method)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Time Percentiles (4 QUERIES SIMULTANEOUSLY)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le, http_route))",
     "legendFormat": "p50 {{http_route}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le, http_route))",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le, http_route))",
     "legendFormat": "p95 {{http_route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le, http_route))",
     "legendFormat": "p99 {{http_route}}"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "# sum(increase(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le)\nsum(rate(http_server_duration_milliseconds_bucket{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Apdex Score (satisfied, tolerating, frustrated, STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "description": "The Apdex (Application Performance Index) measures user satisfaction with application performance, representing it as a normalized value in the range $[0, 1]$. This metric counts the sum of requests that are completely satisfied (Satisfied) and half of requests that are tolerated (Tolerating), and then divides this sum by the total number of requests, including requests that are frustrating (Frustrated). As a result, the closer the Apdex is to $1.0$, the higher the level of perceived performance by users.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "# STEP BY STEP TRIAL:\n# http_server_duration_milliseconds_bucket\n# http_server_duration_milliseconds_bucket{le=\"50.0\"}\n# http_server_duration_milliseconds_bucket{le=\"50.0\", http_route=~\"$route\"}\n# rate(http_server_duration_milliseconds_bucket{le=\"50.0\", http_route=~\"$route\"}[$__rate_interval])\n\n(\n  # Satisfied: Requests <= 50ms (counted as 1.0)\n  sum(rate(http_server_duration_milliseconds_bucket{le=\"50.0\", http_route=~\"$route\"}[$__rate_interval]))\n  +\n  # Tolerating: Requests in (50ms, 250ms] (counted as 0.5)\n  (\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"250.0\", http_route=~\"$route\"}[$__rate_interval]))\n    -\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"50.0\", http_route=~\"$route\"}[$__rate_interval]))\n  ) * 0.5\n)\n/\n# Total: All requests (Satisfied + Tolerating + Frustrated)\nsum(rate(http_server_duration_milliseconds_count{http_route=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  { "title": "Error Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Error Rate (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "description": "This calculates RATE, so there needs to be an INCREASING rate of errors to be displayed here",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# http_server_duration_milliseconds_count{http_status_code=~'[45]..', http_route=~\"$route\", http_method=~\"$method\"}\n# rate(http_server_duration_milliseconds_count{http_status_code=~'[45]..', http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])\n# sum(rate(http_server_duration_milliseconds_count{http_status_code=~'[45]..', http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval]))\n\nsum(rate(http_server_duration_milliseconds_count{http_status_code=~'[45]..', http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval]))\n/\nsum(rate(http_server_duration_milliseconds_count{http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval]))\n*\n100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"5..\", http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Error Count by Status Code (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "# STEP BY STEP TUTORIAL\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\"}[$__rate_interval])\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\"}[$__rate_interval])\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])\n\nsum(rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (http_status_code)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Error Count by Route / Status Code (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "# STEP BY STEP TUTORIAL\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\"}[$__rate_interval])\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\"}[$__rate_interval])\n# rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])\n\nsum(rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\", http_route=~\"$route\", http_method=~\"$method\"}[$__rate_interval])) by (http_route, http_status_code)",
     "legendFormat": "{{http_route}} {{http_status_code}}"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "DB Client Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "db_client_connection_count{exported_job=\"products-api\"}",
     "legendFormat": "{{db_client_connection_state}}({{db_client_connection_pool_name}})"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname='products'}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname='products'}",
     "legendFormat": "{{state}} - {{usename}}"
    }
   ]
  }
 ]
}